from app.database import SessionLocal
from app.models import Category, Provider


def seed_data():
    db = SessionLocal()
    try:
        if db.query(Provider).count() > 100:
            print("Providers already seeded (100+), skipping.")
            return
        print(f"Found {db.query(Provider).count()} providers. Reseeding...")
        db.query(Provider).delete()
        db.query(Category).delete()
        db.commit()

        categories = [
            Category(
                name="Salon & Grooming",
                slug="salon-grooming",
                description="Professional beauty, hair, makeup, and grooming services",
                icon="Scissors",
                image_url="https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80",
            ),
            Category(
                name="Cleaning",
                slug="cleaning",
                description="Expert home and office cleaning services",
                icon="SprayCan",
                image_url="https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&q=80",
            ),
            Category(
                name="Plumbing",
                slug="plumbing",
                description="Reliable plumbing repairs and installations",
                icon="Wrench",
                image_url="https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=600&q=80",
            ),
            Category(
                name="Electrical",
                slug="electrical",
                description="Licensed electricians for all your needs",
                icon="Zap",
                image_url="https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=600&q=80",
            ),
            Category(
                name="Painting",
                slug="painting",
                description="Transform your space with professional painting",
                icon="Paintbrush",
                image_url="https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=600&q=80",
            ),
            Category(
                name="Pest Control",
                slug="pest-control",
                description="Effective pest control solutions for your home",
                icon="Bug",
                image_url="https://images.unsplash.com/photo-1540366244940-9dce0a570312?w=600&q=80",
            ),
            Category(
                name="Maid Service",
                slug="maid-service",
                description="Reliable housekeeping and cleaning services for your home",
                icon="SprayCan",
                image_url="https://images.unsplash.com/photo-1575467678930-c7acd65d6470?w=600&q=80",
            ),
            Category(
                name="Chefs",
                slug="chefs",
                description="Professional chefs and cooking services for any occasion",
                icon="ChefHat",
                image_url="https://images.unsplash.com/photo-1681270543584-8e541a1bb056?w=600&q=80",
            ),
            Category(
                name="AC & Cooling",
                slug="ac-cooling",
                description="AC installation, repair, and maintenance",
                icon="Snowflake",
                image_url="https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80",
            ),
            Category(
                name="Handyman",
                slug="handyman",
                description="General repairs and odd jobs done right",
                icon="Hammer",
                image_url="https://images.unsplash.com/photo-1574359411659-15573a27fd0c?w=600&q=80",
            ),
            Category(
                name="Moving & Packing",
                slug="moving-packing",
                description="Stress-free moving and packing services",
                icon="Truck",
                image_url="https://images.unsplash.com/photo-1600518464441-9154a4dea21b?w=600&q=80",
            ),
        ]
        db.add_all(categories)
        db.flush()

        providers = [
            # ============================================================
            # SALON & GROOMING (11 providers)
            # ============================================================
            Provider(
                name="Enddi Beauty Salon & Makeup",
                slug="enddi-beauty-salon",
                category="Salon & Grooming",
                description="African hair care, braids, weaves, makeup, and bridal looks in Doha. Expert styling, protective styles, and flawless makeup for every occasion.",
                rating=4.9,
                reviews_count=234,
                price_range="QAR 80 - 500",
                phone="+974 6644 4347",
                email="enddibeautysalon@gmail.com",
                skills='["Hair Braiding", "Weaves & Extensions", "Bridal Makeup", "African Hair Care", "Nail Art"]',
            ),
            Provider(
                name="Roots Qatar",
                slug="roots-qatar",
                category="Salon & Grooming",
                description="Blonde specialist salon in Doha. Expert hair cutting, coloring, and treatments. Focus on hair health with careful consultation for your perfect shade.",
                rating=4.8,
                reviews_count=312,
                price_range="QAR 150 - 600",
                phone="+974 4411 4463",
                email="info@rootsqtr.com",
                skills='["Blonde Specialist", "Hair Coloring", "Haircut & Styling", "Hair Treatment", "Consultation"]',
            ),
            Provider(
                name="Te'masq Ladies Salon & Spa",
                slug="temasq-ladies-salon",
                category="Salon & Grooming",
                description="Total transformation salon and spa for ladies. Expert hair stylists, color specialists, facials, and full beauty treatments. Locations at Mall of Qatar and DoubleTree Hilton.",
                rating=4.8,
                reviews_count=198,
                price_range="QAR 200 - 800",
                phone="+974 3157 7777",
                email="info@temasq.com",
                skills='["Hair Styling", "Hair Color", "Facial Treatment", "Spa Services", "Beauty Consultation"]',
            ),
            Provider(
                name="The Clique",
                slug="the-clique-doha",
                category="Salon & Grooming",
                description="Premium hair, nails, and lashes salon owned by master stylist Bassam Rezk. Showcasing artistry and expertise with every haircut, color, and nail service.",
                rating=4.7,
                reviews_count=156,
                price_range="QAR 150 - 700",
                phone="+974 5552 1999",
                email="info@theclique.qa",
                skills='["Haircut & Styling", "Hair Color", "Nail Art", "Lash Extensions", "Bridal Services"]',
            ),
            Provider(
                name="Glam Bar",
                slug="glam-bar-doha",
                category="Salon & Grooming",
                description="Luxurious beauty destination offering organic hair treatments, nail services, and transformative beauty journeys. Locally sourced aloe vera hair treatments available.",
                rating=4.6,
                reviews_count=187,
                price_range="QAR 100 - 500",
                phone="+974 4038 9056",
                email="info@glambar.qa",
                skills='["Organic Hair Treatment", "Manicure", "Pedicure", "Nail Art", "Beauty Treatment"]',
            ),
            Provider(
                name="Eva Beauty Salon",
                slug="eva-beauty-salon",
                category="Salon & Grooming",
                description="Full-service beauty salon offering eyebrow threading, bridal makeup, makeup service, and hair styling. Popular destination in Garafa, Doha.",
                rating=4.5,
                reviews_count=112,
                price_range="QAR 60 - 400",
                phone="+974 5574 4660",
                email="eva.beauty@hotmail.com",
                skills='["Bridal Makeup", "Eyebrow Threading", "Makeup Service", "Hair Styling", "Facial"]',
            ),
            Provider(
                name="La Coupe Salon",
                slug="la-coupe-salon",
                category="Salon & Grooming",
                description="Elegant salon at Dusit D2 Hotel offering professional hair services, threading, and beauty treatments. Known for precision cuts and exceptional customer service.",
                rating=4.4,
                reviews_count=89,
                price_range="QAR 80 - 450",
                phone="+974 3340 0273",
                email="salon@lacoupe.qa",
                skills='["Haircut", "Threading", "Blow Dry", "Hair Color", "Styling"]',
            ),
            Provider(
                name="Nurture & Co Salon",
                slug="nurture-co-salon",
                category="Salon & Grooming",
                description="Eco-friendly salon at Barwa Village offering organic hair treatments, spray tans, lash extensions, facials, and waxing. Focus on sustainable beauty in a relaxing environment.",
                rating=4.7,
                reviews_count=134,
                price_range="QAR 120 - 550",
                phone="+974 4448 5335",
                email="hello@nurturecosalon.com",
                skills='["Organic Hair Care", "Spray Tan", "Lash Extensions", "Facial", "Waxing"]',
            ),
            Provider(
                name="Bombay Brou Salon",
                slug="bombay-brou-salon",
                category="Salon & Grooming",
                description="Indian beauty salon specializing in henna, bridal makeup, threading, and traditional hair treatments. Popular for South Asian bridal packages and skincare.",
                rating=4.6,
                reviews_count=98,
                price_range="QAR 80 - 400",
                phone="+974 3348 6299",
                email="info@bombaybrou.com",
                skills='["Henna Art", "Bridal Makeup", "Threading", "Hair Treatment", "Facial"]',
            ),
            Provider(
                name="Barberette Studio",
                slug="barberette-studio",
                category="Salon & Grooming",
                description="Women's exclusive salon and spa offering haircuts, coloring, keratin treatments, facials, and nail artistry. Known for personalized service and relaxed atmosphere.",
                rating=4.5,
                reviews_count=76,
                price_range="QAR 100 - 450",
                phone="+974 6652 3277",
                email="info@barberette.qa",
                skills='["Haircut", "Keratin Treatment", "Facial", "Nail Art", "Hair Color"]',
            ),
            Provider(
                name="Zahra Al Rayyan Salon",
                slug="zahra-al-rayyan-salon",
                category="Salon & Grooming",
                description="Ladies beauty salon in Al Rayyan offering hair styling, bridal packages, facials, waxing, and nail services. Affordable luxury in a comfortable setting.",
                rating=4.4,
                reviews_count=65,
                price_range="QAR 60 - 350",
                phone="+974 3302 8851",
                email="info@zahra.qa",
                skills='["Hair Styling", "Bridal Package", "Facial", "Waxing", "Nail Service"]',
            ),
            # ============================================================
            # CLEANING (12 providers)
            # ============================================================
            Provider(
                name="Dania Maids",
                slug="dania-maids",
                category="Cleaning",
                description="Qatar's highest-rated cleaning company since 1998. BICSc accredited with over 1,381 five-star reviews. Professional home, villa, and office cleaning at affordable rates starting from 35 QAR/hr.",
                rating=4.9,
                reviews_count=1381,
                price_range="QAR 35 - 180/hr",
                phone="+974 3333 7410",
                email="info@dania-maids.com",
                skills='["Home Cleaning", "Villa Cleaning", "Office Cleaning", "Deep Cleaning", "Eco-Friendly Products"]',
            ),
            Provider(
                name="Qatar Maid Service",
                slug="qatar-maid-service",
                category="Cleaning",
                description="Leading residential and corporate cleaning company in Doha. Professional housekeeping, deep cleaning, and sanitization services with flexible scheduling.",
                rating=4.7,
                reviews_count=423,
                price_range="QAR 80 - 250",
                phone="+974 3024 4939",
                email="info@qatarmaidservice.com",
                skills='["Residential Cleaning", "Deep Cleaning", "Office Cleaning", "Sanitization", "Pool Cleaning"]',
            ),
            Provider(
                name="Scrubs Qatar",
                slug="scrubs-qatar",
                category="Cleaning",
                description="Eco-friendly cleaning services using environmentally safe products. Trained professionals for home, apartment, and villa cleaning across Doha.",
                rating=4.6,
                reviews_count=187,
                price_range="QAR 60 - 200",
                phone="+974 5533 1221",
                email="hello@scrubs.qa",
                skills='["Eco Cleaning", "Home Cleaning", "Deep Cleaning", "Carpet Cleaning", "Move-in/Move-out"]',
            ),
            Provider(
                name="Al Allam Cleaning",
                slug="al-allam-cleaning",
                category="Cleaning",
                description="Professional cleaning and facility management since 2010. Offering house cleaning, office cleaning, steam cleaning, and babysitting services with trained staff.",
                rating=4.5,
                reviews_count=256,
                price_range="QAR 70 - 220",
                phone="+974 4411 5566",
                email="info@alallamcleaning.com",
                skills='["House Cleaning", "Office Cleaning", "Steam Cleaning", "Babysitting", "Laundry & Ironing"]',
            ),
            Provider(
                name="Carla Maid",
                slug="carla-maid",
                category="Cleaning",
                description="Premium home cleaning with carefully vetted, trained maids. Bi-weekly, weekly, and monthly plans available. 4.8-star rated with over 400 verified reviews. Eco-friendly supplies.",
                rating=4.8,
                reviews_count=412,
                price_range="QAR 70 - 220",
                phone="+974 7123 6660",
                email="info@carlamaid.qa",
                skills='["Regular Cleaning", "Deep Cleaning", "Villa Cleaning", "Apartment Cleaning", "Eco-Friendly"]',
            ),
            Provider(
                name="Haya Al Reem Cleaning",
                slug="haya-al-reem-cleaning",
                category="Cleaning",
                description="Trusted cleaning company covering all areas of Doha and Al Rayyan. Home cleaning, deep cleaning, sofa cleaning, and office sanitation with professional-grade equipment.",
                rating=4.6,
                reviews_count=189,
                price_range="QAR 80 - 250",
                phone="+974 5565 6241",
                email="support@hayaalreemqatar.com",
                skills='["Home Cleaning", "Deep Cleaning", "Sofa Cleaning", "Office Sanitization", "Kitchen Deep Clean"]',
            ),
            Provider(
                name="Pick Maid Qatar",
                slug="pick-maid-qatar",
                category="Cleaning",
                description="Affordable cleaning service with trained professionals. House cleaning, babysitting, laundry, ironing, steam cleaning, and upholstery care. Flexible scheduling available.",
                rating=4.5,
                reviews_count=234,
                price_range="QAR 50 - 180",
                phone="+974 7719 9699",
                email="wecare@pickmaid.com",
                skills='["Home Cleaning", "Steam Cleaning", "Laundry & Ironing", "Upholstery Care", "Babysitting"]',
            ),
            Provider(
                name="Hegy International Cleaning",
                slug="hegy-cleaning",
                category="Cleaning",
                description="Professional cleaning and facility management services across Qatar. Specialist in deep cleaning, carpet cleaning, office maintenance, and sanitation for residential and commercial clients.",
                rating=4.6,
                reviews_count=156,
                price_range="QAR 80 - 300",
                phone="+974 3386 5544",
                email="cleaning@hegyqatar.com",
                skills='["Deep Cleaning", "Carpet Cleaning", "Office Cleaning", "Commercial Sanitation", "Sofa Cleaning"]',
            ),
            Provider(
                name="Top Clean Qatar",
                slug="top-clean-qatar",
                category="Cleaning",
                description="Comprehensive cleaning solutions for homes, villas, and businesses. Specializing in deep cleaning, window cleaning, and sanitization. Fully insured and bonded staff.",
                rating=4.4,
                reviews_count=112,
                price_range="QAR 80 - 280",
                phone="+974 5522 2239",
                email="info@topcleanqatar.com",
                skills='["Deep Cleaning", "Window Cleaning", "Villa Cleaning", "Sanitization", "Office Cleaning"]',
            ),
            Provider(
                name="Qatar Cleaning Company",
                slug="qatar-cleaning-company",
                category="Cleaning",
                description="Established cleaning company serving Doha since 2008. Full range of residential and commercial cleaning, including post-construction cleaning, move-in/move-out, and maintenance contracts.",
                rating=4.3,
                reviews_count=87,
                price_range="QAR 90 - 300",
                phone="+974 4466 2695",
                email="info@qatarcleaningcompany.com",
                skills='["Post-Construction", "Move-in/Move-out", "Office Cleaning", "Maintenance Contract", "Villa Cleaning"]',
            ),
            Provider(
                name="Al Zaman Cleaning",
                slug="al-zaman-cleaning",
                category="Cleaning",
                description="Reliable home and office cleaning services with attention to detail. Trained staff, professional equipment, and 100% satisfaction guarantee on every cleaning job.",
                rating=4.5,
                reviews_count=134,
                price_range="QAR 60 - 200",
                phone="+974 5599 7444",
                email="info@alzamancleaning.com",
                skills='["Home Cleaning", "Office Cleaning", "Deep Cleaning", "Carpet Cleaning", "Kitchen Cleaning"]',
            ),
            Provider(
                name="Sparkle Cleaning Services",
                slug="sparkle-cleaning",
                category="Cleaning",
                description="Premium cleaning with a focus on hygiene and sanitation. Using hospital-grade disinfectants and HEPA-filtered vacuums for allergen-free homes. Weekly and bi-weekly plans.",
                rating=4.4,
                reviews_count=98,
                price_range="QAR 80 - 260",
                phone="+974 3322 1144",
                email="info@sparkleqatar.com",
                skills='["Home Cleaning", "Sanitization", "Allergen-Free", "Kitchen & Bathroom", "Weekly Plans"]',
            ),
            # ============================================================
            # PLUMBING (12 providers)
            # ============================================================
            Provider(
                name="Home Service Qatar",
                slug="home-service-qatar",
                category="Plumbing",
                description="Expert plumbing services with 24/7 emergency response. Leak detection, pipe repair, water heater installation, and complete bathroom renovations. Certified plumbers.",
                rating=4.8,
                reviews_count=312,
                price_range="QAR 150 - 800",
                phone="+974 6643 1046",
                email="haquekamal42@gmail.com",
                skills='["Leak Detection", "Pipe Repair", "Water Heater Install", "Drain Cleaning", "Bathroom Renovation"]',
            ),
            Provider(
                name="Fixit Qatar",
                slug="fixit-qatar",
                category="Plumbing",
                description="Premium plumbing and maintenance services for homes and businesses. Full plumbing system diagnostics, repairs, and installations with guaranteed workmanship.",
                rating=4.7,
                reviews_count=198,
                price_range="QAR 180 - 750",
                phone="+974 3133 4948",
                email="helpdesk@fixitqatar.com",
                skills='["Full Plumbing", "Fixture Install", "Water Pressure Fix", "Sewer Line", "Emergency Service"]',
            ),
            Provider(
                name="Homefix Qatar",
                slug="homefix-qatar",
                category="Plumbing",
                description="All-in-one home maintenance with expert plumbing. Fast response for leaky faucets, burst pipes, toilet repairs, and complete bathroom fitting. Affordable fixed pricing.",
                rating=4.6,
                reviews_count=145,
                price_range="QAR 120 - 600",
                phone="+974 7401 4822",
                email="info@homefixqatar.com",
                skills='["Faucet Repair", "Toilet Repair", "Pipe Fixing", "Bathroom Fitting", "Water Tank Install"]',
            ),
            Provider(
                name="Plumber Service Doha",
                slug="plumber-service-doha",
                category="Plumbing",
                description="Fast and reliable plumbing services across Doha. Specializing in emergency repairs, drain cleaning, water heater installation, and complete plumbing system overhauls. Same-day service.",
                rating=4.8,
                reviews_count=276,
                price_range="QAR 120 - 700",
                phone="+974 5123 8070",
                email="plumberservicedoha@gmail.com",
                skills='["Emergency Repair", "Drain Cleaning", "Water Heater", "Pipe Repair", "Bathroom Fitting"]',
            ),
            Provider(
                name="Doha Plumber Service",
                slug="doha-plumber-service",
                category="Plumbing",
                description="Certified plumbers for residential and commercial plumbing. Leak detection, sewer line repair, water tank installation, and bathroom renovations. Available 24/7 for emergencies.",
                rating=4.7,
                reviews_count=198,
                price_range="QAR 130 - 750",
                phone="+974 6630 4542",
                email="dohaplumberservice@gmail.com",
                skills='["Leak Detection", "Sewer Line Repair", "Water Tank Install", "Bathroom Renovation", "Emergency 24/7"]',
            ),
            Provider(
                name="Plumbing Doha",
                slug="plumbing-doha",
                category="Plumbing",
                description="Professional plumbing company serving all areas of Doha. Expert installation and repair of faucets, toilets, showers, water heaters, and sewage systems. Quality guaranteed.",
                rating=4.6,
                reviews_count=156,
                price_range="QAR 150 - 700",
                phone="+974 7144 0620",
                email="info@plumbingdoha.com",
                skills='["Faucet Install", "Toilet Repair", "Shower System", "Sewage Repair", "Water Heater"]',
            ),
            Provider(
                name="Qatar Home Solutions",
                slug="qatar-home-solutions",
                category="Plumbing",
                description="Complete home maintenance with dedicated plumbing division. Full bathroom renovations, pipe replacement, drainage solutions, and preventive maintenance contracts for homes and villas.",
                rating=4.5,
                reviews_count=112,
                price_range="QAR 150 - 800",
                phone="+974 7768 1856",
                email="info@qatarhomesolutions.com",
                skills='["Bathroom Renovation", "Pipe Replacement", "Drainage Service", "Preventive Maintenance", "Villa Plumbing"]',
            ),
            Provider(
                name="Doha Home Fix",
                slug="doha-home-fix-plumbing",
                category="Plumbing",
                description="Reliable plumbing repairs and installations. Expert leak detection, pipe fixing, toilet and faucet repair, water heater services, and complete bathroom solutions. Quick response.",
                rating=4.7,
                reviews_count=167,
                price_range="QAR 100 - 650",
                phone="+974 7446 9660",
                email="info@dohahomefix.com",
                skills='["Leak Detection", "Pipe Fixing", "Toilet Repair", "Faucet Service", "Water Heater"]',
            ),
            Provider(
                name="Qatar Home Maintenance",
                slug="qatar-home-maintenance-plumbing",
                category="Plumbing",
                description="Professional plumbing maintenance and repair services. Full system diagnostics, emergency repairs, water pressure solutions, and annual maintenance contracts available.",
                rating=4.5,
                reviews_count=89,
                price_range="QAR 130 - 600",
                phone="+974 3130 1315",
                email="info@qatarhomemaintenance.com",
                skills='["System Diagnostics", "Emergency Repair", "Water Pressure", "Pipe Service", "Annual Contract"]',
            ),
            Provider(
                name="Express Fix Qatar",
                slug="express-fix-qatar-plumbing",
                category="Plumbing",
                description="Fast plumbing solutions with same-day service. Emergency call-outs, leak detection, drain unblocking, toilet repair, and complete bathroom fitting. No call-out fee.",
                rating=4.6,
                reviews_count=123,
                price_range="QAR 120 - 600",
                phone="+974 5117 8245",
                email="info@expressfixqatar.com",
                skills='["Same-Day Service", "Drain Unblocking", "Emergency Call-out", "Toilet Repair", "Bathroom Fitting"]',
            ),
            Provider(
                name="Al Wukair Plumbing Services",
                slug="al-wukair-plumbing",
                category="Plumbing",
                description="Trusted plumbing services covering Al Wukair and greater Doha. Specialist in new installation, maintenance, and emergency plumbing for residential and commercial properties.",
                rating=4.4,
                reviews_count=67,
                price_range="QAR 150 - 700",
                phone="+974 5004 7171",
                email="info@alwukairplumbing.com",
                skills='["New Installation", "Maintenance", "Emergency Plumbing", "Residential Service", "Commercial Service"]',
            ),
            Provider(
                name="Al Khor Plumbing",
                slug="al-khor-plumbing",
                category="Plumbing",
                description="Serving Al Khor and northern Qatar with expert plumbing solutions. Full range of plumbing services from minor repairs to complete system installations. Competitive rates.",
                rating=4.3,
                reviews_count=54,
                price_range="QAR 130 - 650",
                phone="+974 5533 4455",
                email="info@alkhorplumbing.com",
                skills='["General Plumbing", "System Install", "Minor Repair", "Water Tank", "Pipe Service"]',
            ),
            # ============================================================
            # ELECTRICAL (12 providers)
            # ============================================================
            Provider(
                name="Handyman Doha",
                slug="handyman-doha-electrical",
                category="Electrical",
                description="Professional electrical repair and installation services. Lighting, switches, sockets, wiring, and electrical fixing. Same-day service available across Doha.",
                rating=4.8,
                reviews_count=276,
                price_range="QAR 100 - 500",
                phone="+974 3332 0402",
                email="info@handymandoha.com",
                skills='["Lighting Install", "Switch Repair", "Wiring Work", "Socket Fixing", "Electrical Safety Check"]',
            ),
            Provider(
                name="Fixit Qatar",
                slug="fixit-qatar-electrical",
                category="Electrical",
                description="Licensed electricians for residential and commercial electrical work. Panel upgrades, rewiring, inspection, and smart home installation. Safety certified.",
                rating=4.7,
                reviews_count=167,
                price_range="QAR 150 - 700",
                phone="+974 3133 4948",
                email="helpdesk@fixitqatar.com",
                skills='["Panel Upgrade", "Rewiring", "Smart Home Setup", "Inspection", "Generator Connection"]',
            ),
            Provider(
                name="Homefix Qatar",
                slug="homefix-qatar-electrical",
                category="Electrical",
                description="Comprehensive electrical maintenance and repair. Switchboard repair, ceiling fan installation, emergency power solutions, and complete home rewiring.",
                rating=4.5,
                reviews_count=98,
                price_range="QAR 120 - 600",
                phone="+974 7401 4822",
                email="info@homefixqatar.com",
                skills='["Fan Installation", "Switchboard Repair", "Emergency Electric", "Ceiling Light Fix", "Wiring Upgrade"]',
            ),
            Provider(
                name="Doha Home Fix",
                slug="doha-home-fix-electrical",
                category="Electrical",
                description="Expert electrical services for homes and offices. Lighting installation, switch and socket repair, circuit breaker upgrades, and full electrical safety inspections.",
                rating=4.7,
                reviews_count=145,
                price_range="QAR 100 - 550",
                phone="+974 7446 9660",
                email="info@dohahomefix.com",
                skills='["Lighting Install", "Switch Repair", "Circuit Breaker", "Safety Inspection", "Socket Fix"]',
            ),
            Provider(
                name="Qatar Home Solutions",
                slug="qatar-home-solutions-electrical",
                category="Electrical",
                description="Full electrical services including panel installation, rewiring, smart home automation, and emergency repairs. Licensed and experienced electricians for all projects.",
                rating=4.5,
                reviews_count=98,
                price_range="QAR 150 - 700",
                phone="+974 7768 1856",
                email="info@qatarhomesolutions.com",
                skills='["Panel Install", "Rewiring", "Smart Home", "Emergency Repair", "Lighting Design"]',
            ),
            Provider(
                name="Qatar Home Maintenance",
                slug="qatar-home-maintenance-electrical",
                category="Electrical",
                description="Reliable electrical maintenance, inspections, fault finding, and repair. Ceiling fan installation, lighting upgrades, and safety checks for peace of mind.",
                rating=4.4,
                reviews_count=76,
                price_range="QAR 120 - 550",
                phone="+974 3130 1315",
                email="info@qatarhomemaintenance.com",
                skills='["Fault Finding", "Fan Installation", "Lighting Upgrade", "Safety Check", "Maintenance"]',
            ),
            Provider(
                name="Express Fix Qatar",
                slug="express-fix-qatar-electrical",
                category="Electrical",
                description="Fast electrical repair and installation services. Emergency electrician available 24/7. All types of electrical work from minor repairs to full rewiring projects.",
                rating=4.5,
                reviews_count=87,
                price_range="QAR 100 - 500",
                phone="+974 5117 8245",
                email="info@expressfixqatar.com",
                skills='["Emergency Electric", "Rewiring", "Light Repair", "Socket Install", "Switch Fix"]',
            ),
            Provider(
                name="Plumber Service Doha",
                slug="plumber-service-doha-electrical",
                category="Electrical",
                description="Combined plumbing and electrical services for complete home maintenance. Certified electricians for lighting, wiring, switchboards, and emergency electrical repairs.",
                rating=4.6,
                reviews_count=134,
                price_range="QAR 120 - 600",
                phone="+974 5123 8070",
                email="plumberservicedoha@gmail.com",
                skills='["Lighting Service", "Wiring Fix", "Switchboard", "Emergency Electric", "Combined Service"]',
            ),
            Provider(
                name="Al Sadd Electric",
                slug="al-sadd-electric",
                category="Electrical",
                description="Professional electrical services in Al Sadd and central Doha. Specializing in residential rewiring, commercial electrical maintenance, and emergency call-outs.",
                rating=4.4,
                reviews_count=78,
                price_range="QAR 130 - 600",
                phone="+974 5511 2233",
                email="info@alsaddelectric.com",
                skills='["Residential Rewiring", "Commercial Maintenance", "Emergency Call-out", "Lighting", "Panel Work"]',
            ),
            Provider(
                name="Doha Electrician Pro",
                slug="doha-electrician-pro",
                category="Electrical",
                description="Expert electrical contractors for residential and commercial projects. Full electrical design, installation, testing, and certification. Smart home and automation specialists.",
                rating=4.5,
                reviews_count=92,
                price_range="QAR 150 - 800",
                phone="+974 5544 6677",
                email="info@doelectrician.com",
                skills='["Electrical Design", "Installation", "Testing & Certification", "Smart Home", "Automation"]',
            ),
            Provider(
                name="Al Rayyan Electrical Services",
                slug="al-rayyan-electrical",
                category="Electrical",
                description="Reliable electrical services covering Al Rayyan and west Doha. Generator installation, electrical panel upgrades, lighting solutions, and 24/7 emergency support.",
                rating=4.4,
                reviews_count=67,
                price_range="QAR 150 - 750",
                phone="+974 5577 8899",
                email="info@alrayyanelectrical.com",
                skills='["Generator Install", "Panel Upgrade", "Lighting", "Emergency 24/7", "Villa Electrical"]',
            ),
            # ============================================================
            # PAINTING (10 providers)
            # ============================================================
            Provider(
                name="Homefix Qatar",
                slug="homefix-qatar-painting",
                category="Painting",
                description="Professional painting and decorating services for homes, villas, offices, and shops. Interior and exterior painting with premium materials and color consultation.",
                rating=4.7,
                reviews_count=134,
                price_range="QAR 200 - 1200",
                phone="+974 7401 4822",
                email="info@homefixqatar.com",
                skills='["Interior Painting", "Exterior Painting", "Color Consultation", "Wallpaper Install", "Texture Finish"]',
            ),
            Provider(
                name="Handyman Doha",
                slug="handyman-doha-painting",
                category="Painting",
                description="Quality painting and wall repair with professional finishing. Touch-ups, full room painting, crack repair, and decorative finishes. Quick and clean service.",
                rating=4.6,
                reviews_count=87,
                price_range="QAR 180 - 1000",
                phone="+974 3332 0402",
                email="info@handymandoha.com",
                skills='["Wall Painting", "Crack Repair", "Touch-ups", "Ceiling Painting", "Decorative Finish"]',
            ),
            Provider(
                name="Home Service Qatar",
                slug="home-service-qatar-painting",
                category="Painting",
                description="Complete painting solutions for residential and commercial properties. Professional prep work, premium paints, and meticulous attention to detail. Free quotes.",
                rating=4.5,
                reviews_count=72,
                price_range="QAR 200 - 1100",
                phone="+974 6643 1046",
                email="haquekamal42@gmail.com",
                skills='["House Painting", "Office Painting", "Wood Staining", "Waterproof Paint", "Free Quote"]',
            ),
            Provider(
                name="Doha Home Fix",
                slug="doha-home-fix-painting",
                category="Painting",
                description="Interior and exterior painting with professional finish. Wall crack repair, ceiling painting, wallpaper removal and installation. Color matching and consultation included.",
                rating=4.6,
                reviews_count=98,
                price_range="QAR 180 - 1000",
                phone="+974 7446 9660",
                email="info@dohahomefix.com",
                skills='["Interior Paint", "Exterior Paint", "Wall Crack Repair", "Wallpaper Service", "Color Matching"]',
            ),
            Provider(
                name="Qatar Home Solutions",
                slug="qatar-home-solutions-painting",
                category="Painting",
                description="Full-service painting company for residential and commercial projects. Surface preparation, priming, painting, and finishing with premium materials and experienced painters.",
                rating=4.4,
                reviews_count=67,
                price_range="QAR 200 - 1200",
                phone="+974 7768 1856",
                email="info@qatarhomesolutions.com",
                skills='["Surface Prep", "Priming & Painting", "Commercial Paint", "Residential Paint", "Texture Coating"]',
            ),
            Provider(
                name="Qatar Home Maintenance",
                slug="qatar-home-maintenance-painting",
                category="Painting",
                description="Professional painting maintenance for homes and offices. Regular touch-ups, full repaints, waterproofing, and decorative finishes. Free color consultation and quotes.",
                rating=4.3,
                reviews_count=56,
                price_range="QAR 200 - 1000",
                phone="+974 3130 1315",
                email="info@qatarhomemaintenance.com",
                skills='["Touch-ups", "Full Repaint", "Waterproofing", "Color Consult", "Decorative Finish"]',
            ),
            Provider(
                name="Express Fix Qatar",
                slug="express-fix-qatar-painting",
                category="Painting",
                description="Quick and professional painting services for homes and businesses. Same-day quotes, fast turnaround, quality finishes, and clean work sites. All paint brands available.",
                rating=4.5,
                reviews_count=78,
                price_range="QAR 180 - 1000",
                phone="+974 5117 8245",
                email="info@expressfixqatar.com",
                skills='["Quick Painting", "Home Painting", "Office Painting", "Same-Day Quote", "Clean Finish"]',
            ),
            Provider(
                name="Color World Painting",
                slug="color-world-painting",
                category="Painting",
                description="Specialist painting company with expertise in decorative finishes, textured walls, and custom color schemes. Premium paints and meticulous attention to detail for luxury homes.",
                rating=4.6,
                reviews_count=112,
                price_range="QAR 250 - 1500",
                phone="+974 5522 3344",
                email="info@colorworldqatar.com",
                skills='["Decorative Finish", "Texture Wall", "Custom Color", "Luxury Home", "Premium Paint"]',
            ),
            Provider(
                name="Al Jazeera Painters",
                slug="al-jazeera-painters",
                category="Painting",
                description="One of Qatar's most trusted painting companies. Large-scale villa painting, office complexes, and residential projects. European-trained painters with premium materials.",
                rating=4.5,
                reviews_count=134,
                price_range="QAR 200 - 1400",
                phone="+974 5566 7788",
                email="info@aljazeerapainters.com",
                skills='["Villa Painting", "Office Complex", "Residential Project", "European Finish", "Large Scale"]',
            ),
            Provider(
                name="Doha Painting Pros",
                slug="doha-painting-pros",
                category="Painting",
                description="Professional painting contractors serving all Doha. Interior, exterior, commercial, and industrial painting. Fully insured, free estimates, and satisfaction guaranteed.",
                rating=4.4,
                reviews_count=89,
                price_range="QAR 180 - 1100",
                phone="+974 5533 1122",
                email="info@dohapaintingpros.com",
                skills='["Interior Paint", "Exterior Paint", "Commercial Paint", "Industrial Paint", "Free Estimate"]',
            ),
            # ============================================================
            # PEST CONTROL (10 providers)
            # ============================================================
            Provider(
                name="Al Allam Pest Control",
                slug="al-allam-pest-control",
                category="Pest Control",
                description="Effective pest control services as part of comprehensive facility management. Cockroach, ant, termite, and rodent elimination. Safe for families and pets.",
                rating=4.6,
                reviews_count=178,
                price_range="QAR 250 - 800",
                phone="+974 4411 5566",
                email="info@alallamcleaning.com",
                skills='["Cockroach Control", "Termite Treatment", "Rodent Control", "Ant Elimination", "Fumigation"]',
            ),
            Provider(
                name="Homefix Pest Control",
                slug="homefix-qatar-pest",
                category="Pest Control",
                description="Residential and commercial pest management with integrated approach. Monthly and quarterly maintenance plans available. 100% satisfaction guaranteed.",
                rating=4.4,
                reviews_count=63,
                price_range="QAR 200 - 700",
                phone="+974 7401 4822",
                email="info@homefixqatar.com",
                skills='["Maintenance Plans", "Spider Control", "Fly Control", "Mosquito Treatment", "Prevention Tips"]',
            ),
            Provider(
                name="Hegy Pest Control",
                slug="hegy-pest-control",
                category="Pest Control",
                description="Professional pest management with over 15 years experience in Qatar. Complete pest elimination for cockroaches, termites, bed bugs, rodents, and mosquitoes. Family-safe treatments.",
                rating=4.6,
                reviews_count=145,
                price_range="QAR 250 - 900",
                phone="+974 3386 5544",
                email="pest@hegyqatar.com",
                skills='["Cockroach Control", "Termite Control", "Bed Bug Treatment", "Rodent Control", "Mosquito Control"]',
            ),
            Provider(
                name="Al Miqyas Pest Control",
                slug="al-miqyas-pest-control",
                category="Pest Control",
                description="ISO-certified pest control company serving Doha and all Qatar. Specialized in termite treatment, fumigation, and general pest control. Environmentally responsible methods.",
                rating=4.5,
                reviews_count=134,
                price_range="QAR 250 - 850",
                phone="+974 4478 8398",
                email="info@almiqyas.com",
                skills='["Termite Treatment", "Fumigation", "General Pest Control", "Mosquito Control", "Fly Control"]',
            ),
            Provider(
                name="National Pest Control Qatar",
                slug="national-pest-control",
                category="Pest Control",
                description="Qatar's leading pest management company with over 20 years experience. Comprehensive pest control for residential, commercial, and industrial clients. Licensed and insured.",
                rating=4.5,
                reviews_count=198,
                price_range="QAR 250 - 900",
                phone="+974 4455 6677",
                email="info@nationalpestqatar.com",
                skills='["Comprehensive Pest Control", "Commercial Service", "Industrial Service", "Residential Service", "Fumigation"]',
            ),
            Provider(
                name="Al Taif Pest Control",
                slug="al-taif-pest-control",
                category="Pest Control",
                description="Trusted pest management services with eco-friendly solutions. Cockroach, ant, termite, bed bug, and rodent control for homes and businesses across Doha.",
                rating=4.4,
                reviews_count=112,
                price_range="QAR 200 - 800",
                phone="+974 5555 6677",
                email="info@altaifpest.com",
                skills='["Eco-Friendly Control", "Cockroach Control", "Ant Control", "Bed Bug Control", "Rodent Control"]',
            ),
            Provider(
                name="Bio Care Pest Control",
                slug="bio-care-pest-control",
                category="Pest Control",
                description="Environmentally conscious pest control using bio-friendly products. Effective against all common pests while being safe for children, pets, and plants. Monthly plans available.",
                rating=4.5,
                reviews_count=89,
                price_range="QAR 220 - 800",
                phone="+974 5522 3344",
                email="info@biocareqatar.com",
                skills='["Bio-Friendly Treatment", "Child Safe", "Pet Safe", "Monthly Plans", "All Pest Types"]',
            ),
            Provider(
                name="Safe Pest Control Doha",
                slug="safe-pest-control-doha",
                category="Pest Control",
                description="Family-safe pest elimination with guaranteed results. Complete treatment for cockroaches, ants, spiders, bed bugs, termites, and rodents. Free inspection and quote.",
                rating=4.3,
                reviews_count=76,
                price_range="QAR 200 - 750",
                phone="+974 5566 7788",
                email="info@safepestqatar.com",
                skills='["Family Safe", "Free Inspection", "Cockroach", "Termite", "Rodent"]',
            ),
            Provider(
                name="Al Wajba Pest Control",
                slug="al-wajba-pest-control",
                category="Pest Control",
                description="Serving Al Wajba and greater Doha with professional pest management. Specialized treatment plans for villas, apartments, and commercial properties. Fast response.",
                rating=4.4,
                reviews_count=67,
                price_range="QAR 200 - 800",
                phone="+974 5588 9900",
                email="info@alwajbapest.com",
                skills='["Villa Treatment", "Apartment Service", "Commercial Pest", "Fast Response", "All Pests"]',
            ),
            Provider(
                name="Apex Pest Control Qatar",
                slug="apex-pest-control",
                category="Pest Control",
                description="Premium pest elimination services with advanced technology. Heat treatment for bed bugs, termite baiting systems, and eco-friendly general pest control. Warranty on all treatments.",
                rating=4.5,
                reviews_count=98,
                price_range="QAR 250 - 1000",
                phone="+974 5599 0011",
                email="info@apexpestqatar.com",
                skills='["Heat Treatment", "Termite Baiting", "Eco-Friendly", "Bed Bug Service", "Treatment Warranty"]',
            ),
            # ============================================================
            # MAID SERVICE (10 providers)
            # ============================================================
            Provider(
                name="Dania Maids",
                slug="dania-maids-service",
                category="Maid Service",
                description="Qatar's most trusted maid service since 1998. 4.9-star rating with over 1,381 reviews. Background-checked Filipino cleaners, eco-friendly products, AI-powered booking.",
                rating=4.9,
                reviews_count=1381,
                price_range="QAR 35 - 150/hr",
                phone="+974 3333 7410",
                email="info@dania-maids.com",
                skills='["House Cleaning", "Villa Cleaning", "Deep Cleaning", "Regular Cleaning", "Eco-Friendly"]',
            ),
            Provider(
                name="Qatar Maid Service",
                slug="qatar-maid-service-maid",
                category="Maid Service",
                description="Premium maid and housekeeping services for homes, villas, and apartments in Doha. Regular cleaning, deep cleaning, and custom packages with flexible timing.",
                rating=4.7,
                reviews_count=532,
                price_range="QAR 60 - 200",
                phone="+974 3024 4939",
                email="info@qatarmaidservice.com",
                skills='["Full House Cleaning", "Deep Cleaning", "Regular Maintenance", "Kitchen Cleaning", "Bathroom Cleaning"]',
            ),
            Provider(
                name="Pick Maid Qatar",
                slug="pick-maid-qatar-maid",
                category="Maid Service",
                description="Affordable maid service with trained professionals. House cleaning, babysitting, laundry, ironing, steam cleaning, and upholstery care. Flexible scheduling available.",
                rating=4.5,
                reviews_count=234,
                price_range="QAR 50 - 180",
                phone="+974 7719 9699",
                email="wecare@pickmaid.com",
                skills='["Home Cleaning", "Babysitting", "Laundry & Ironing", "Steam Cleaning", "Upholstery Care"]',
            ),
            Provider(
                name="Scrubs Maid Service",
                slug="scrubs-maid-service",
                category="Maid Service",
                description="Eco-friendly maid service using non-toxic cleaning products. Trained housekeepers for regular cleaning, deep cleaning, and specialized tasks. Safe for kids and pets.",
                rating=4.6,
                reviews_count=156,
                price_range="QAR 60 - 200",
                phone="+974 5533 1221",
                email="hello@scrubs.qa",
                skills='["Regular Housekeeping", "Deep Cleaning", "Eco-Friendly", "Pet Safe", "Child Safe"]',
            ),
            Provider(
                name="Carla Maid Service",
                slug="carla-maid-service",
                category="Maid Service",
                description="Premium maid service with carefully matched, vetted cleaners. Weekly, bi-weekly, and monthly housekeeping plans. All supplies provided. Satisfaction guaranteed on every visit.",
                rating=4.8,
                reviews_count=378,
                price_range="QAR 70 - 220",
                phone="+974 7123 6660",
                email="info@carlamaid.qa",
                skills='["Weekly Housekeeping", "Bi-Weekly Plans", "Monthly Cleaning", "All Supplies", "Cleaning Match"]',
            ),
            Provider(
                name="Haya Al Reem Maids",
                slug="haya-al-reem-maids",
                category="Maid Service",
                description="Professional housekeeping services for homes and villas in Doha and Al Rayyan. Experienced maids, flexible schedules, and thorough cleaning at affordable hourly rates.",
                rating=4.6,
                reviews_count=167,
                price_range="QAR 50 - 180",
                phone="+974 5565 6241",
                email="support@hayaalreemqatar.com",
                skills='["Housekeeping", "Villa Service", "Flexible Schedule", "Hourly Rate", "Thorough Cleaning"]',
            ),
            Provider(
                name="Top Clean Maids",
                slug="top-clean-maids",
                category="Maid Service",
                description="Professional maid placement and cleaning service. All maids are trained, insured, and background-checked. One-time deep cleaning or recurring service available.",
                rating=4.4,
                reviews_count=98,
                price_range="QAR 60 - 200",
                phone="+974 5522 2239",
                email="info@topcleanqatar.com",
                skills='["Maid Placement", "Background Checked", "Deep Cleaning", "Recurring Service", "One-Time Cleaning"]',
            ),
            Provider(
                name="Al Zaman Household Services",
                slug="al-zaman-household",
                category="Maid Service",
                description="Dedicated household staff and cleaning services. Full-time and part-time maid arrangements, housekeeping, laundry, ironing, and general home care. Arabic and English speaking.",
                rating=4.5,
                reviews_count=112,
                price_range="QAR 50 - 200",
                phone="+974 5599 7444",
                email="info@alzamancleaning.com",
                skills='["Full-Time Maid", "Part-Time Maid", "Housekeeping", "Laundry", "General Home Care"]',
            ),
            Provider(
                name="Sparkle Home Services",
                slug="sparkle-home-services",
                category="Maid Service",
                description="Hotel-standard housekeeping for your home. Trained professionals using premium products and equipment. Regular weekly visits keep your home consistently spotless.",
                rating=4.4,
                reviews_count=76,
                price_range="QAR 80 - 260",
                phone="+974 3322 1144",
                email="info@sparkleqatar.com",
                skills='["Hotel Standard", "Weekly Service", "Premium Products", "Consistent Care", "Full Home Service"]',
            ),
            Provider(
                name="Al Allam Maids",
                slug="al-allam-maids",
                category="Maid Service",
                description="Full maid and housekeeping services as part of complete facility management. Trained cleaning staff for homes, villas, and apartments. Laundry, ironing, and babysitting included.",
                rating=4.5,
                reviews_count=198,
                price_range="QAR 60 - 200",
                phone="+974 4411 5566",
                email="info@alallamcleaning.com",
                skills='["Full Maid Service", "Housekeeping", "Laundry & Ironing", "Babysitting", "Villa Service"]',
            ),
            # ============================================================
            # CHEFS (10 providers)
            # ============================================================
            Provider(
                name="Layla Kitchen",
                slug="layla-kitchen",
                category="Chefs",
                description="Premium catering and private dining services in Doha. Specializing in corporate events, weddings, intimate gatherings, and daily meal subscriptions. Exquisite cuisine.",
                rating=4.9,
                reviews_count=178,
                price_range="QAR 200 - 800",
                phone="+974 5566 7788",
                email="info@layla-kitchen.com",
                skills='["Corporate Catering", "Private Dining", "Wedding Catering", "Daily Meal Plan", "Pastry Service"]',
            ),
            Provider(
                name="Take a Chef Doha",
                slug="take-a-chef-doha",
                category="Chefs",
                description="Platform connecting 90+ professional private chefs in Doha. Personalized menus for any occasion. From intimate dinners to large celebrations. Chef shops, cooks, and cleans up.",
                rating=4.8,
                reviews_count=98,
                price_range="QAR 250 - 1000",
                phone="+974 5077 8899",
                email="hello@takeachef.com",
                skills='["Private Chef", "Custom Menus", "Event Catering", "Cooking Class", "Dietary Planning"]',
            ),
            Provider(
                name="MiumMium Qatar",
                slug="miummium-qatar",
                category="Chefs",
                description="Voted best private chef experience. Professional chefs for romantic dinners, cooking classes, bachelorette parties, and weekly meal prep. Full service from shopping to cleanup.",
                rating=4.7,
                reviews_count=67,
                price_range="QAR 300 - 1200",
                phone="+974 5088 9900",
                email="doha@miummium.com",
                skills='["Romantic Dinner", "Cooking Class", "Meal Prep", "Party Catering", "Wine Pairing"]',
            ),
            Provider(
                name="Chef on Call Doha",
                slug="chef-on-call-doha",
                category="Chefs",
                description="Professional chefs available for private dining, events, and weekly meal preparation. Customized menus, dietary accommodations, and full service from kitchen to table.",
                rating=4.6,
                reviews_count=54,
                price_range="QAR 250 - 900",
                phone="+974 5599 0011",
                email="info@chefoncalldoha.com",
                skills='["Private Dining", "Event Service", "Weekly Meal Prep", "Dietary Accommodation", "Full Service"]',
            ),
            Provider(
                name="My Personal Chef Qatar",
                slug="my-personal-chef-qatar",
                category="Chefs",
                description="Personal chef services for families and individuals. Weekly meal planning, grocery shopping, cooking, and kitchen clean-up. Healthy, delicious meals tailored to your preferences.",
                rating=4.5,
                reviews_count=45,
                price_range="QAR 200 - 800",
                phone="+974 5511 2233",
                email="info@mypersonalchefqatar.com",
                skills='["Meal Planning", "Weekly Service", "Healthy Cooking", "Grocery Service", "Clean-up"]',
            ),
            Provider(
                name="Home Gourmet Qatar",
                slug="home-gourmet-qatar",
                category="Chefs",
                description="Luxury in-home dining experiences with Michelin-trained chefs. Multi-course tasting menus, wine pairing, and elegant presentation for special occasions and celebrations.",
                rating=4.7,
                reviews_count=78,
                price_range="QAR 350 - 1500",
                phone="+974 5522 3344",
                email="info@homegourmetqatar.com",
                skills='["Michelin Chefs", "Tasting Menu", "Wine Pairing", "Special Occasion", "In-Home Dining"]',
            ),
            Provider(
                name="Doha Private Chefs",
                slug="doha-private-chefs",
                category="Chefs",
                description="Expert private chefs for intimate dinners, parties, and corporate events. International cuisine specialists. Fresh ingredients, custom menus, and impeccable presentation.",
                rating=4.6,
                reviews_count=67,
                price_range="QAR 250 - 1000",
                phone="+974 5533 4455",
                email="info@dohaprivatechefs.com",
                skills='["Intimate Dinner", "Party Service", "Corporate Event", "International Cuisine", "Custom Menu"]',
            ),
            Provider(
                name="Feast Catering Qatar",
                slug="feast-catering",
                category="Chefs",
                description="Full-service catering for events of all sizes. From small gatherings to large celebrations. Buffet, set menu, and live cooking station options. Exceptional food and service.",
                rating=4.5,
                reviews_count=89,
                price_range="QAR 150 - 600",
                phone="+974 5544 5566",
                email="info@feastcatering.qa",
                skills='["Event Catering", "Buffet Service", "Set Menu", "Live Cooking", "Large Events"]',
            ),
            Provider(
                name="Catering by Chef",
                slug="catering-by-chef",
                category="Chefs",
                description="Bespoke catering services for corporate events, weddings, and private parties. Experienced culinary team creating memorable dining experiences with premium ingredients.",
                rating=4.4,
                reviews_count=56,
                price_range="QAR 180 - 700",
                phone="+974 5555 6677",
                email="info@cateringbychef.com",
                skills='["Corporate Catering", "Wedding Catering", "Private Party", "Premium Ingredients", "Bespoke Menu"]',
            ),
            Provider(
                name="Al Fanar Catering",
                slug="al-fanar-catering",
                category="Chefs",
                description="Authentic Arabic and international catering services. Specializing in traditional Qatari cuisine, mixed grills, and Arabic mezza for events, offices, and home gatherings.",
                rating=4.5,
                reviews_count=98,
                price_range="QAR 120 - 500",
                phone="+974 5566 7788",
                email="info@alfanarcatering.com",
                skills='["Arabic Cuisine", "Qatari Traditional", "Mixed Grill", "Event Service", "Office Catering"]',
            ),
            # ============================================================
            # AC & COOLING (10 providers)
            # ============================================================
            Provider(
                name="Homefix Qatar",
                slug="homefix-qatar-ac",
                category="AC & Cooling",
                description="AC installation, moving, repair, and maintenance. Water leak fixing, gas filling, compressor change, and complete AC servicing for all brands including LG, Samsung, Daikin.",
                rating=4.8,
                reviews_count=245,
                price_range="QAR 180 - 1500",
                phone="+974 7401 4822",
                email="info@homefixqatar.com",
                skills='["AC Installation", "AC Repair", "Gas Refill", "Compressor Fix", "AC Moving"]',
            ),
            Provider(
                name="Handyman Doha",
                slug="handyman-doha-ac",
                category="AC & Cooling",
                description="AC cleaning, servicing, installation support, and maintenance assistance. Quick response for emergency cooling issues across Doha and all Qatar.",
                rating=4.6,
                reviews_count=112,
                price_range="QAR 150 - 600",
                phone="+974 3332 0402",
                email="info@handymandoha.com",
                skills='["AC Cleaning", "AC Service", "AC Installation", "Duct Cleaning", "Filter Replacement"]',
            ),
            Provider(
                name="Home Service Qatar",
                slug="home-service-qatar-ac",
                category="AC & Cooling",
                description="Professional AC servicing and repair with 24/7 emergency support. Split AC, central AC, and ducted system maintenance. Energy efficiency optimization.",
                rating=4.5,
                reviews_count=89,
                price_range="QAR 200 - 1000",
                phone="+974 6643 1046",
                email="haquekamal42@gmail.com",
                skills='["Split AC Service", "Central AC", "Emergency Repair", "Energy Optimization", "Thermostat Setup"]',
            ),
            Provider(
                name="Doha Home Fix",
                slug="doha-home-fix-ac",
                category="AC & Cooling",
                description="Complete AC solutions including installation, repair, and maintenance for all major brands. Gas refill, compressor repair, duct cleaning, and emergency cooling services.",
                rating=4.7,
                reviews_count=134,
                price_range="QAR 150 - 1200",
                phone="+974 7446 9660",
                email="info@dohahomefix.com",
                skills='["AC Install", "AC Repair", "Gas Refill", "Compressor Repair", "Duct Cleaning"]',
            ),
            Provider(
                name="Qatar Home Solutions",
                slug="qatar-home-solutions-ac",
                category="AC & Cooling",
                description="Professional air conditioning services for residential and commercial properties. Installation, maintenance, repair, and energy efficiency audits for all AC systems.",
                rating=4.5,
                reviews_count=78,
                price_range="QAR 200 - 1300",
                phone="+974 7768 1856",
                email="info@qatarhomesolutions.com",
                skills='["AC Install", "Maintenance", "Repair", "Energy Audit", "Commercial AC"]',
            ),
            Provider(
                name="Qatar Home Maintenance",
                slug="qatar-home-maintenance-ac",
                category="AC & Cooling",
                description="Reliable AC maintenance and repair services. Filter cleaning, gas refilling, compressor checks, and full AC servicing. Annual maintenance contracts for peace of mind.",
                rating=4.4,
                reviews_count=67,
                price_range="QAR 180 - 1000",
                phone="+974 3130 1315",
                email="info@qatarhomemaintenance.com",
                skills='["Filter Cleaning", "Gas Refill", "Compressor Check", "Full Service", "Annual Contract"]',
            ),
            Provider(
                name="Express Fix Qatar",
                slug="express-fix-qatar-ac",
                category="AC & Cooling",
                description="Fast AC repair and servicing with same-day response. Emergency cooling repairs, gas refilling, compressor replacement, and AC installation for homes and offices.",
                rating=4.5,
                reviews_count=92,
                price_range="QAR 150 - 1000",
                phone="+974 5117 8245",
                email="info@expressfixqatar.com",
                skills='["Same-Day Repair", "Emergency Cooling", "Gas Refill", "Compressor Replacement", "Installation"]',
            ),
            Provider(
                name="Al Rayyan AC Services",
                slug="al-rayyan-ac",
                category="AC & Cooling",
                description="Specialist AC services covering Al Rayyan, Al Wajba, and west Doha. Expert installation of split units, ducted systems, and central AC. Maintenance contracts available.",
                rating=4.4,
                reviews_count=87,
                price_range="QAR 200 - 1200",
                phone="+974 5511 2233",
                email="info@alrayyanac.com",
                skills='["Split Unit Install", "Ducted System", "Central AC", "Maintenance Contract", "West Doha Service"]',
            ),
            Provider(
                name="Doha AC Maintenance",
                slug="doha-ac-maintenance",
                category="AC & Cooling",
                description="Your trusted AC maintenance partner in Doha. Comprehensive servicing for all AC types including window units, split systems, and central AC. Fast, reliable, affordable.",
                rating=4.5,
                reviews_count=112,
                price_range="QAR 150 - 900",
                phone="+974 5522 3344",
                email="info@dohaac.com",
                skills='["Window AC", "Split System", "Central AC", "Comprehensive Service", "Affordable"]',
            ),
            Provider(
                name="Al Sadd Cooling Services",
                slug="al-sadd-cooling",
                category="AC & Cooling",
                description="Premium AC services in Al Sadd and central Doha. Installation, repair, and maintenance for residential and commercial clients. Daikin, LG, Samsung, and Gree specialists.",
                rating=4.3,
                reviews_count=56,
                price_range="QAR 200 - 1200",
                phone="+974 5533 4455",
                email="info@alsaddcooling.com",
                skills='["Brand Specialist", "Residential AC", "Commercial AC", "Installation", "Repair"]',
            ),
            # ============================================================
            # HANDYMAN (12 providers)
            # ============================================================
            Provider(
                name="Handyman Doha",
                slug="handyman-doha-main",
                category="Handyman",
                description="Trusted handyman company across Doha and all Qatar. Reliable repair, installation, and maintenance for homes and offices. Furniture assembly, TV mounting, door locks, and more.",
                rating=4.8,
                reviews_count=376,
                price_range="QAR 100 - 500",
                phone="+974 3332 0402",
                email="info@handymandoha.com",
                skills='["Furniture Assembly", "TV Mounting", "Door Repair", "General Repairs", "Shelf Installation"]',
            ),
            Provider(
                name="Homefix Qatar",
                slug="homefix-qatar-handyman",
                category="Handyman",
                description="One-stop solution for all home maintenance. Tile work, gypsum decoration, curtain installation, sofa upholstery, carpentry, and general handyman services.",
                rating=4.7,
                reviews_count=234,
                price_range="QAR 120 - 550",
                phone="+974 7401 4822",
                email="info@homefixqatar.com",
                skills='["Carpentry", "Tiling", "Gypsum Work", "Curtain Install", "Upholstery"]',
            ),
            Provider(
                name="Home Service Qatar",
                slug="home-service-qatar-handyman",
                category="Handyman",
                description="Complete house maintenance service with 24/7 availability. Plumbing, electrical, carpentry, painting, tile installation, and general repair solutions. Fast response.",
                rating=4.6,
                reviews_count=156,
                price_range="QAR 100 - 500",
                phone="+974 6643 1046",
                email="haquekamal42@gmail.com",
                skills='["General Maintenance", "Carpentry", "Tile Install", "Painting", "Emergency Repairs"]',
            ),
            Provider(
                name="Fixit Qatar",
                slug="fixit-qatar-handyman",
                category="Handyman",
                description="Hourly handyman service for all household repairs. Tile repairs, window seals, appliance fixing, shelf mounting, and more. Send us your task list.",
                rating=4.5,
                reviews_count=89,
                price_range="QAR 100 - 450",
                phone="+974 3133 4948",
                email="helpdesk@fixitqatar.com",
                skills='["Task List Service", "Appliance Repair", "Window Seal", "Tile Repair", "Shelf Mounting"]',
            ),
            Provider(
                name="Doha Home Fix",
                slug="doha-home-fix-handyman",
                category="Handyman",
                description="Your go-to handyman for home repairs and improvements. Furniture assembly, TV mounting, painting, plumbing fixes, electrical work, and general maintenance. One call does it all.",
                rating=4.7,
                reviews_count=189,
                price_range="QAR 100 - 500",
                phone="+974 7446 9660",
                email="info@dohahomefix.com",
                skills='["Furniture Assembly", "TV Mounting", "Painting", "Plumbing Fix", "Electrical Work"]',
            ),
            Provider(
                name="Qatar Home Solutions",
                slug="qatar-home-solutions-handyman",
                category="Handyman",
                description="Full-service home maintenance and repair. Expert handymen for carpentry, painting, tiling, plumbing, electrical, and general odd jobs. Quality workmanship at fair prices.",
                rating=4.5,
                reviews_count=112,
                price_range="QAR 100 - 500",
                phone="+974 7768 1856",
                email="info@qatarhomesolutions.com",
                skills='["Carpentry", "Painting", "Tiling", "Plumbing", "Electrical"]',
            ),
            Provider(
                name="Qatar Home Maintenance",
                slug="qatar-home-maintenance-handyman",
                category="Handyman",
                description="Reliable handyman for all household tasks. From fixing leaky faucets to assembling furniture, mounting TVs to painting walls. Professional, prompt, and affordable.",
                rating=4.4,
                reviews_count=78,
                price_range="QAR 100 - 450",
                phone="+974 3130 1315",
                email="info@qatarhomemaintenance.com",
                skills='["Faucet Repair", "Furniture Assembly", "TV Mounting", "Wall Painting", "General Fix"]',
            ),
            Provider(
                name="Express Fix Qatar",
                slug="express-fix-qatar-handyman",
                category="Handyman",
                description="Quick and reliable handyman services across Doha. Same-day service for urgent repairs, furniture assembly, TV installation, curtain hanging, and general home maintenance.",
                rating=4.5,
                reviews_count=98,
                price_range="QAR 100 - 450",
                phone="+974 5117 8245",
                email="info@expressfixqatar.com",
                skills='["Same-Day Service", "Furniture Assembly", "TV Install", "Curtain Hanging", "Urgent Repair"]',
            ),
            Provider(
                name="Mr Fix It Qatar",
                slug="mr-fix-it-qatar",
                category="Handyman",
                description="Experienced handyman covering all aspects of home repair and maintenance. Carpentry, plumbing, electrical, painting, and general fixing. No job too small. Free quotes.",
                rating=4.5,
                reviews_count=87,
                price_range="QAR 100 - 500",
                phone="+974 5544 6677",
                email="info@mrfixitqatar.com",
                skills='["Carpentry", "Plumbing", "Electrical", "Painting", "Free Quote"]',
            ),
            Provider(
                name="Al Sadd Handyman",
                slug="al-sadd-handyman",
                category="Handyman",
                description="Trusted handyman team serving Al Sadd and central Doha. Expert in furniture assembly, home repairs, painting, tiling, and maintenance. Reliable and affordable service.",
                rating=4.3,
                reviews_count=56,
                price_range="QAR 100 - 450",
                phone="+974 5555 7788",
                email="info@alsaddhandyman.com",
                skills='["Furniture Assembly", "Home Repair", "Painting", "Tiling", "Maintenance"]',
            ),
            Provider(
                name="Doha Task Master",
                slug="doha-task-master",
                category="Handyman",
                description="Professional handyman service for all your to-do list. Assembly, installation, repairs, and odd jobs. Hourly or per-task pricing. Experienced and fully equipped team.",
                rating=4.4,
                reviews_count=67,
                price_range="QAR 100 - 500",
                phone="+974 5566 8899",
                email="info@dohataskmaster.com",
                skills='["Assembly Service", "Installation", "Repairs", "Odd Jobs", "Hourly or Per Task"]',
            ),
            # ============================================================
            # MOVING & PACKING (10 providers)
            # ============================================================
            Provider(
                name="Almas Movers International",
                slug="almas-movers",
                category="Moving & Packing",
                description="ISO-certified moving company since 2011. Residential, commercial, and international relocation services. IAM accredited with expert packing, transport, and setup.",
                rating=4.9,
                reviews_count=567,
                price_range="QAR 600 - 4000",
                phone="+974 4435 5663",
                email="movers@almasintl.com",
                skills='["Home Relocation", "Office Moving", "International Move", "Packing Service", "Furniture Setup"]',
            ),
            Provider(
                name="Qatar Movers and Packers",
                slug="qatar-movers-packers",
                category="Moving & Packing",
                description="Best moving company with expert packing, loading, and transportation across Doha, Al Khor, Lusail, and all Qatar. Fast, safe, and affordable relocation services.",
                rating=4.7,
                reviews_count=342,
                price_range="QAR 500 - 3000",
                phone="+974 3119 2915",
                email="info@qatarmoversandpackers.com",
                skills='["Home Relocation", "Office Shifting", "Furniture Moving", "Packing & Unpacking", "Loading Services"]',
            ),
            Provider(
                name="E-Movers Qatar",
                slug="e-movers-qatar",
                category="Moving & Packing",
                description="ISO 9001:2015 certified relocation company. Specializing in home relocation, office relocation, storage, and furniture installation. 80%+ customer satisfaction rate.",
                rating=4.6,
                reviews_count=198,
                price_range="QAR 500 - 3500",
                phone="+974 4476 2244",
                email="info@emoversqatar.com",
                skills='["Home Relocation", "Office Relocation", "Storage", "Furniture Install", "International Move"]',
            ),
            Provider(
                name="Moving Company Doha Qatar",
                slug="moving-company-doha",
                category="Moving & Packing",
                description="Reliable local movers since 2009. House, villa, apartment moving, and relocation services. Professional packing materials delivery and furniture disassembly included.",
                rating=4.5,
                reviews_count=123,
                price_range="QAR 400 - 2500",
                phone="+974 7183 7300",
                email="info@movingcompanydohaqatar.com",
                skills='["House Moving", "Villa Moving", "Apartment Moving", "Box Delivery", "Furniture Disassembly"]',
            ),
            Provider(
                name="Al Adharaj Movers",
                slug="al-adharaj-movers",
                category="Moving & Packing",
                description="Established moving company with professional relocation services. Home and office moving, packing materials, furniture assembly, and storage solutions. Fully insured.",
                rating=4.6,
                reviews_count=145,
                price_range="QAR 500 - 3000",
                phone="+974 4460 3333",
                email="info@aladharaj.com",
                skills='["Home Moving", "Office Moving", "Packing Materials", "Storage", "Furniture Assembly"]',
            ),
            Provider(
                name="Al Jaber Moving Services",
                slug="al-jaber-moving",
                category="Moving & Packing",
                description="Professional relocation services for homes, villas, and offices. Expert packing, careful handling, and timely delivery. Competitive rates with full insurance coverage.",
                rating=4.5,
                reviews_count=112,
                price_range="QAR 450 - 2800",
                phone="+974 4411 2266",
                email="info@aljabermoving.com",
                skills='["Home Relocation", "Villa Moving", "Office Moving", "Packing Service", "Insurance Cover"]',
            ),
            Provider(
                name="Doha Relocation Services",
                slug="doha-relocation",
                category="Moving & Packing",
                description="Stress-free relocation for families and businesses. End-to-end moving solutions including packing, loading, transport, unloading, and furniture setup. Storage available.",
                rating=4.4,
                reviews_count=89,
                price_range="QAR 500 - 3000",
                phone="+974 5544 5566",
                email="info@doharelocation.com",
                skills='["Full Service Moving", "Packing & Loading", "Transport", "Furniture Setup", "Storage"]',
            ),
            Provider(
                name="Qatar Moving Solutions",
                slug="qatar-moving-solutions",
                category="Moving & Packing",
                description="Comprehensive moving services across Doha and all Qatar. Specialized in apartment and villa moving, with custom packing solutions for fragile and valuable items.",
                rating=4.5,
                reviews_count=98,
                price_range="QAR 400 - 2500",
                phone="+974 5555 6677",
                email="info@qatarmovingsolutions.com",
                skills='["Apartment Moving", "Villa Moving", "Fragile Packing", "Valuables Service", "All Qatar"]',
            ),
            Provider(
                name="Al Sadd Movers",
                slug="al-sadd-movers",
                category="Moving & Packing",
                description="Local movers in Al Sadd with affordable rates. Quick and efficient moving for apartments, villas, and offices. Free packing materials with full moving packages.",
                rating=4.3,
                reviews_count=67,
                price_range="QAR 350 - 2200",
                phone="+974 5566 7788",
                email="info@alsaddmovers.com",
                skills='["Local Moving", "Apartment Service", "Villa Moving", "Office Moving", "Free Packing"]',
            ),
            Provider(
                name="Lusail Packing & Moving",
                slug="lusail-packing-moving",
                category="Moving & Packing",
                description="Premium moving and packing services focused on Lusail and north Doha. White-glove service with careful handling, custom crating, and priority scheduling for luxury residences.",
                rating=4.5,
                reviews_count=78,
                price_range="QAR 600 - 3500",
                phone="+974 5577 8899",
                email="info@lusailpacking.com",
                skills='["Luxury Moving", "Custom Crating", "White-Glove Service", "Lusail Focus", "Priority Service"]',
            ),
        ]
        db.add_all(providers)
        db.commit()
    finally:
        db.close()
