from app.database import SessionLocal
from app.models import Category, Provider


def seed_data():
    db = SessionLocal()
    try:
        if db.query(Category).count() > 0:
            return

        categories = [
            Category(
                name="Salon & Grooming",
                slug="salon-grooming",
                description="Professional beauty, hair, makeup, and grooming services",
                icon="Scissors",
                image_url="https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80",
            ),
            Category(
                name="Cleaning",
                slug="cleaning",
                description="Expert home and office cleaning services",
                icon="SprayCan",
                image_url="https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&q=80",
            ),
            Category(
                name="Plumbing",
                slug="plumbing",
                description="Reliable plumbing repairs and installations",
                icon="Wrench",
                image_url="https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=600&q=80",
            ),
            Category(
                name="Electrical",
                slug="electrical",
                description="Licensed electricians for all your needs",
                icon="Zap",
                image_url="https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=600&q=80",
            ),
            Category(
                name="Painting",
                slug="painting",
                description="Transform your space with professional painting",
                icon="Paintbrush",
                image_url="https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=600&q=80",
            ),
            Category(
                name="Pest Control",
                slug="pest-control",
                description="Effective pest control solutions for your home",
                icon="Bug",
                image_url="https://images.unsplash.com/photo-1540366244940-9dce0a570312?w=600&q=80",
            ),
            Category(
                name="Maid Service",
                slug="maid-service",
                description="Reliable housekeeping and cleaning services for your home",
                icon="SprayCan",
                image_url="https://images.unsplash.com/photo-1575467678930-c7acd65d6470?w=600&q=80",
            ),
            Category(
                name="Chefs",
                slug="chefs",
                description="Professional chefs and cooking services for any occasion",
                icon="ChefHat",
                image_url="https://images.unsplash.com/photo-1681270543584-8e541a1bb056?w=600&q=80",
            ),
            Category(
                name="AC & Cooling",
                slug="ac-cooling",
                description="AC installation, repair, and maintenance",
                icon="Snowflake",
                image_url="https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80",
            ),
            Category(
                name="Handyman",
                slug="handyman",
                description="General repairs and odd jobs done right",
                icon="Hammer",
                image_url="https://images.unsplash.com/photo-1574359411659-15573a27fd0c?w=600&q=80",
            ),
            Category(
                name="Moving & Packing",
                slug="moving-packing",
                description="Stress-free moving and packing services",
                icon="Truck",
                image_url="https://images.unsplash.com/photo-1600518464441-9154a4dea21b?w=600&q=80",
            ),
        ]
        db.add_all(categories)
        db.flush()

        maid_providers = [
            Provider(
                name="Sparkle Home Services",
                slug="sparkle-home-services",
                category="Maid Service",
                description="Thorough home cleaning and maid services with eco-friendly products. Weekly, bi-weekly, or one-time deep cleaning options available.",
                rating=4.7,
                reviews_count=98,
                price_range="QAR 60 - 180",
                phone="+974 5098 7654",
                email="sparkle@qserv.qa",
                skills='["General Cleaning", "Deep Cleaning", "Kitchen Cleaning", "Bathroom Scrubbing", "Laundry"]',
            ),
            Provider(
                name="Crystal Clean Maids",
                slug="crystal-clean-maids",
                category="Maid Service",
                description="Premium maid services with trained and vetted professionals. Fully equipped with modern cleaning tools and supplies.",
                rating=4.8,
                reviews_count=76,
                price_range="QAR 80 - 220",
                phone="+974 5076 5432",
                email="crystal@qserv.qa",
                skills='["Full House Cleaning", "Dusting", "Mopping", "Window Cleaning", "Organizing"]',
            ),
        ]

        chef_providers = [
            Provider(
                name="Gourmet Home Chefs",
                slug="gourmet-home-chefs",
                category="Chefs",
                description="Experienced chefs who prepare restaurant-quality meals in your home. Specializing in international cuisines and dietary requirements.",
                rating=4.9,
                reviews_count=54,
                price_range="QAR 200 - 600",
                phone="+974 5054 3210",
                email="gourmet@qserv.qa",
                skills='["International Cuisine", "Meal Prep", "Private Dining", "Dietary Planning", "Event Catering"]',
            ),
            Provider(
                name="Saffron Personal Chefs",
                slug="saffron-personal-chefs",
                category="Chefs",
                description="Personal chef services for daily meals, special occasions, and dinner parties. Fresh ingredients, customized menus.",
                rating=4.8,
                reviews_count=42,
                price_range="QAR 250 - 700",
                phone="+974 5043 2109",
                email="saffron@qserv.qa",
                skills='["Arabic Cuisine", "Asian Fusion", "Grill & BBQ", "Dessert Making", "Wine Pairing"]',
            ),
        ]

        salon_providers = [
            Provider(
                name="Luminous Nail Studio",
                slug="luminous-nail-studio",
                category="Salon & Grooming",
                description="Premium nail art, manicure, pedicure, and gel extensions in a relaxing studio setting. Using only top-brand products for lasting results.",
                rating=4.8,
                reviews_count=127,
                price_range="QAR 80 - 250",
                phone="+974 5012 3456",
                email="luminous@qserv.qa",
                skills='["Manicure", "Pedicure", "Gel Extensions", "Nail Art", "Paraffin Treatment"]',
            ),
            Provider(
                name="The Hair Lounge",
                slug="the-hair-lounge",
                category="Salon & Grooming",
                description="Expert haircuts, styling, coloring, and treatments for men and women. International-trained stylists in a modern salon environment.",
                rating=4.7,
                reviews_count=98,
                price_range="QAR 60 - 350",
                phone="+974 5023 4567",
                email="hairlounge@qserv.qa",
                skills='["Haircut & Styling", "Hair Coloring", "Keratin Treatment", "Blow Dry", "Hair Extensions"]',
            ),
            Provider(
                name="Glamour Touch Makeup",
                slug="glamour-touch-makeup",
                category="Salon & Grooming",
                description="Professional makeup artistry for weddings, events, and photoshoots. Airbrush, HD makeup, and beauty consultations available.",
                rating=4.9,
                reviews_count=156,
                price_range="QAR 200 - 800",
                phone="+974 5034 5678",
                email="glamourtouch@qserv.qa",
                skills='["Bridal Makeup", "Airbrush Makeup", "Event Makeup", "Makeup Consultation", "HD Makeup"]',
            ),
            Provider(
                name="Serenity Massage Spa",
                slug="serenity-massage-spa",
                category="Salon & Grooming",
                description="Therapeutic and relaxation massage services including Swedish, deep tissue, hot stone, and aromatherapy. Fully licensed therapists.",
                rating=4.8,
                reviews_count=112,
                price_range="QAR 150 - 500",
                phone="+974 5045 6789",
                email="serenity@qserv.qa",
                skills='["Swedish Massage", "Deep Tissue", "Hot Stone Therapy", "Aromatherapy", "Sports Massage"]',
            ),
            Provider(
                name="Modern Gents Barbers",
                slug="modern-gents-barbers",
                category="Salon & Grooming",
                description="Premium barbering services specializing in modern cuts, beard grooming, hot towel shaves, and grooming packages for the modern gentleman.",
                rating=4.6,
                reviews_count=84,
                price_range="QAR 50 - 180",
                phone="+974 5056 7890",
                email="moderngents@qserv.qa",
                skills='["Haircut", "Beard Grooming", "Hot Towel Shave", "Hair Tattoo", "Grooming Package"]',
            ),
            Provider(
                name="Radiant Skin Studio",
                slug="radiant-skin-studio",
                category="Salon & Grooming",
                description="Advanced facial treatments, skin analysis, microdermabrasion, and chemical peels. Customized skincare plans for all skin types.",
                rating=4.7,
                reviews_count=93,
                price_range="QAR 120 - 400",
                phone="+974 5067 8901",
                email="radiant@qserv.qa",
                skills='["Classic Facial", "Microdermabrasion", "Chemical Peel", "Skin Analysis", "Anti-Aging Treatment"]',
            ),
            Provider(
                name="Elegance Bridal Studio",
                slug="elegance-bridal-studio",
                category="Salon & Grooming",
                description="Complete bridal beauty packages including hair, makeup, mehndi, and draping. Trial sessions and wedding day coordination included.",
                rating=4.9,
                reviews_count=68,
                price_range="QAR 500 - 2000",
                phone="+974 5078 9012",
                email="elegancebridal@qserv.qa",
                skills='["Bridal Hair", "Bridal Makeup", "Mehndi Design", "Draping", "Trial Session"]',
            ),
        ]
        providers = [
            Provider(
                name="Sparkle Clean Co.",
                slug="sparkle-clean-co",
                category="Cleaning",
                description="Professional cleaning expert with over 12 years of experience in deep cleaning, move-in/move-out cleaning, and office sanitation. Fully equipped with eco-friendly products.",
                rating=4.9,
                reviews_count=203,
                price_range="QAR 150 - 400",
                phone="+974 3312 4567",
                email="sparkle@qserv.qa",
                skills='["Deep Cleaning", "Office Cleaning", "Move-in/Move-out", "Sanitization"]',
            ),
            Provider(
                name="FreshStart Services",
                slug="freshstart-services",
                category="Cleaning",
                description="Specialized in residential cleaning with meticulous attention to detail. Trained in modern cleaning techniques and customer satisfaction guaranteed.",
                rating=4.8,
                reviews_count=156,
                price_range="QAR 120 - 350",
                phone="+974 3345 6789",
                email="freshstart@qserv.qa",
                skills='["Residential Cleaning", "Kitchen Deep Clean", "Bathroom Scrubbing", "Window Cleaning"]',
            ),
            Provider(
                name="EcoShine Qatar",
                slug="ecoshine-qatar",
                category="Cleaning",
                description="Eco-friendly cleaning specialist using only non-toxic products. Perfect for families with children and pets. Certified green cleaning professional.",
                rating=4.7,
                reviews_count=98,
                price_range="QAR 130 - 380",
                phone="+974 3322 4455",
                email="ecoshine@qserv.qa",
                skills='["Eco-Friendly Cleaning", "Pet-Safe Cleaning", "Upholstery Care", "Tile & Grout"]',
            ),
            Provider(
                name="AquaFix Pro",
                slug="aquafix-pro",
                category="Plumbing",
                description="Licensed master plumber with 18 years of experience handling everything from leaky faucets to full bathroom renovations. Emergency services available.",
                rating=4.9,
                reviews_count=178,
                price_range="QAR 200 - 800",
                phone="+974 3355 6677",
                email="aquafix@qserv.qa",
                skills='["Pipe Repair", "Water Heater", "Drain Cleaning", "Bathroom Installation"]',
            ),
            Provider(
                name="DrainMaster Qatar",
                slug="drainmaster-qatar",
                category="Plumbing",
                description="Expert in commercial and residential plumbing. Specializes in leak detection, pipe fitting, and emergency repairs. Available 24/7 for urgent calls.",
                rating=4.7,
                reviews_count=134,
                price_range="QAR 180 - 750",
                phone="+974 3366 7788",
                email="drainmaster@qserv.qa",
                skills='["Leak Detection", "Pipe Fitting", "Emergency Repair", "Fixture Installation"]',
            ),
            Provider(
                name="PipePerfect Services",
                slug="pipeperfect-services",
                category="Plumbing",
                description="Affordable plumbing solutions without compromising quality. Fixed pricing with no hidden fees. Same-day service for most residential jobs.",
                rating=4.6,
                reviews_count=89,
                price_range="QAR 150 - 600",
                phone="+974 3377 8899",
                email="pipeperfect@qserv.qa",
                skills='["Faucet Repair", "Toilet Installation", "Pipe Replacement", "Water Pressure"]',
            ),
            Provider(
                name="VoltCare Electrical",
                slug="voltcare-electrical",
                category="Electrical",
                description="Certified electrician with 15 years of experience. Expert in wiring, panel upgrades, smart home installation, and troubleshooting complex electrical issues.",
                rating=4.8,
                reviews_count=167,
                price_range="QAR 200 - 900",
                phone="+974 3388 9900",
                email="voltcare@qserv.qa",
                skills='["Wiring & Rewiring", "Panel Upgrade", "Smart Home Setup", "Lighting Installation"]',
            ),
            Provider(
                name="BrightSpark Electric",
                slug="brightspark-electric",
                category="Electrical",
                description="Specializes in commercial electrical projects and home automation. Fully licensed and insured. All work meets Qatar's electrical safety standards.",
                rating=4.7,
                reviews_count=112,
                price_range="QAR 220 - 1000",
                phone="+974 3399 0011",
                email="brightspark@qserv.qa",
                skills='["Commercial Electrical", "Home Automation", "Safety Inspection", "Generator Setup"]',
            ),
            Provider(
                name="QuickPower Solutions",
                slug="quickpower-solutions",
                category="Electrical",
                description="Quick-response electrical services for emergencies. Fan installation, switchboard repairs, and full home rewiring. Transparent pricing guaranteed.",
                rating=4.5,
                reviews_count=76,
                price_range="QAR 180 - 700",
                phone="+974 3300 1122",
                email="quickpower@qserv.qa",
                skills='["Emergency Repairs", "Fan Installation", "Switchboard Repair", "Ceiling Light Fixing"]',
            ),
            Provider(
                name="ColorCraft Studio",
                slug="colorcraft-studio",
                category="Painting",
                description="Professional painter with artistic flair. Interior and exterior painting, textured finishes, and wall paper installation. Color consultation included.",
                rating=4.9,
                reviews_count=145,
                price_range="QAR 250 - 1500",
                phone="+974 3311 2233",
                email="colorcraft@qserv.qa",
                skills='["Interior Painting", "Exterior Painting", "Texture Finishes", "Wallpaper Installation"]',
            ),
            Provider(
                name="BrushMaster Pro",
                slug="brushmaster-pro",
                category="Painting",
                description="15 years of painting experience across residential and commercial projects. Premium paints and meticulous prep work for lasting results.",
                rating=4.7,
                reviews_count=93,
                price_range="QAR 200 - 1200",
                phone="+974 3322 3344",
                email="brushmaster@qserv.qa",
                skills='["Residential Painting", "Commercial Painting", "Wood Staining", "Waterproof Coating"]',
            ),
            Provider(
                name="PaintElegance",
                slug="paintelegance",
                category="Painting",
                description="Affordable painting services with premium quality. Fast turnaround without compromising on detail. Free quote and color samples provided.",
                rating=4.6,
                reviews_count=67,
                price_range="QAR 180 - 1000",
                phone="+974 3344 5566",
                email="paintelegance@qserv.qa",
                skills='["Budget Painting", "Room Makeovers", "Ceiling Painting", "Trim & Molding"]',
            ),
            Provider(
                name="Shield Pest Control",
                slug="shield-pest-control",
                category="Pest Control",
                description="Licensed pest control technician with expertise in cockroach, ant, termite, and bed bug elimination. Safe for families and pets. Follow-up inspection included.",
                rating=4.8,
                reviews_count=192,
                price_range="QAR 300 - 800",
                phone="+974 3355 6677",
                email="shield@qserv.qa",
                skills='["Cockroach Control", "Termite Treatment", "Bed Bug Removal", "Ant Elimination"]',
            ),
            Provider(
                name="EcoGuard Pest Solutions",
                slug="ecoguard-pest-solutions",
                category="Pest Control",
                description="Specialized in commercial pest management for restaurants, hotels, and offices. Integrated pest management approach using eco-friendly methods.",
                rating=4.7,
                reviews_count=88,
                price_range="QAR 350 - 1200",
                phone="+974 3366 7788",
                email="ecoguard@qserv.qa",
                skills='["Commercial Pest Control", "Rodent Control", "Mosquito Treatment", "Fumigation"]',
            ),
            Provider(
                name="SafeHome Pest Management",
                slug="safehome-pest-management",
                category="Pest Control",
                description="Residential pest control specialist. Monthly and quarterly maintenance plans available. 100% satisfaction guaranteed with free re-treatment if needed.",
                rating=4.5,
                reviews_count=56,
                price_range="QAR 250 - 700",
                phone="+974 3377 8899",
                email="safehome@qserv.qa",
                skills='["Maintenance Plans", "Spider Control", "Fly Control", "Prevention Tips"]',
            ),
            Provider(
                name="ArcticFlow Cooling",
                slug="arcticflow-cooling",
                category="AC & Cooling",
                description="HVAC expert with 20+ years in AC installation, repair, and maintenance. Certified by major AC brands. Fast diagnostics and reliable repairs.",
                rating=4.9,
                reviews_count=234,
                price_range="QAR 200 - 1500",
                phone="+974 3388 9900",
                email="arcticflow@qserv.qa",
                skills='["AC Installation", "AC Repair", "Maintenance Service", "Gas Refill"]',
            ),
            Provider(
                name="DuctClean HVAC",
                slug="ductclean-hvac",
                category="AC & Cooling",
                description="Specialized in duct cleaning, AC deep cleaning, and air quality improvement. Helps reduce electricity bills with efficient AC maintenance.",
                rating=4.7,
                reviews_count=123,
                price_range="QAR 180 - 600",
                phone="+974 3399 0011",
                email="ductclean@qserv.qa",
                skills='["Duct Cleaning", "AC Deep Clean", "Air Quality Check", "Filter Replacement"]',
            ),
            Provider(
                name="ChillZone AC Services",
                slug="chillzone-ac-services",
                category="AC & Cooling",
                description="Emergency AC repair service with same-day response. Works on all brands including LG, Samsung, Daikin, and Carrier. Competitive pricing.",
                rating=4.6,
                reviews_count=91,
                price_range="QAR 200 - 1000",
                phone="+974 3300 1122",
                email="chillzone@qserv.qa",
                skills='["Emergency Repair", "Brand Service", "Compressor Fix", "Thermostat Setup"]',
            ),
            Provider(
                name="FixIt Handyman",
                slug="fixit-handyman",
                category="Handyman",
                description="Your one-stop handyman for all household repairs. Furniture assembly, TV mounting, shelf installation, door repairs, and more. No job too small.",
                rating=4.8,
                reviews_count=178,
                price_range="QAR 100 - 500",
                phone="+974 3311 2233",
                email="fixit@qserv.qa",
                skills='["Furniture Assembly", "TV Mounting", "Shelf Installation", "Door Repair"]',
            ),
            Provider(
                name="ProTask Handyman",
                slug="protask-handyman",
                category="Handyman",
                description="Experienced handyman with a wide skill set including carpentry, tiling, and general maintenance. Reliable, punctual, and fully equipped for any job.",
                rating=4.7,
                reviews_count=104,
                price_range="QAR 120 - 550",
                phone="+974 3322 3344",
                email="protask@qserv.qa",
                skills='["Carpentry", "Tiling", "General Maintenance", "Caulking & Sealing"]',
            ),
            Provider(
                name="QuickFix Qatar",
                slug="quickfix-qatar",
                category="Handyman",
                description="Quick-fix specialist for urgent household issues. Leaky roofs, broken tiles, stuck doors, and more. Same-day service at affordable fixed rates.",
                rating=4.5,
                reviews_count=72,
                price_range="QAR 100 - 450",
                phone="+974 3344 5566",
                email="quickfix@qserv.qa",
                skills='["Roof Repair", "Tile Fixing", "Door Adjustment", "Gutter Cleaning"]',
            ),
            Provider(
                name="SmoothMove Qatar",
                slug="smoothmove-qatar",
                category="Moving & Packing",
                description="Professional moving team with 10+ years of experience. Careful packing, loading, transport, and unpacking. Full insurance coverage for peace of mind.",
                rating=4.8,
                reviews_count=156,
                price_range="QAR 500 - 2500",
                phone="+974 3355 6677",
                email="smoothmove@qserv.qa",
                skills='["Residential Moving", "Packing Service", "Furniture Disassembly", "Unpacking & Setup"]',
            ),
            Provider(
                name="PackNShift Pro",
                slug="packnshift-pro",
                category="Moving & Packing",
                description="Affordable moving solutions for apartments and villas. Fully trained crew with all equipment. Free quote and no hidden charges.",
                rating=4.6,
                reviews_count=89,
                price_range="QAR 400 - 2000",
                phone="+974 3366 7788",
                email="packnshift@qserv.qa",
                skills='["Apartment Moving", "Villa Moving", "Packing Materials", "Loading & Unloading"]',
            ),
            Provider(
                name="WhiteGlove Movers",
                slug="whiteglove-movers",
                category="Moving & Packing",
                description="Premium white-glove moving service. We handle everything from fragile items to heavy furniture with utmost care. Climate-controlled storage available.",
                rating=4.9,
                reviews_count=67,
                price_range="QAR 800 - 4000",
                phone="+974 3377 8899",
                email="whiteglove@qserv.qa",
                skills='["Premium Moving", "Fragile Handling", "Storage Service", "Piano Moving"]',
            ),
        ]
        db.add_all(providers + salon_providers + maid_providers + chef_providers)
        db.commit()
    finally:
        db.close()
