from app.database import SessionLocal
from app.models import Category, Provider


def seed_data():
    db = SessionLocal()
    try:
        if db.query(Category).count() > 0:
            return

        categories = [
            Category(
                name="Salon & Grooming",
                slug="salon-grooming",
                description="Professional beauty, hair, makeup, and grooming services",
                icon="Scissors",
                image_url="https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&q=80",
            ),
            Category(
                name="Cleaning",
                slug="cleaning",
                description="Expert home and office cleaning services",
                icon="SprayCan",
                image_url="https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&q=80",
            ),
            Category(
                name="Plumbing",
                slug="plumbing",
                description="Reliable plumbing repairs and installations",
                icon="Wrench",
                image_url="https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=600&q=80",
            ),
            Category(
                name="Electrical",
                slug="electrical",
                description="Licensed electricians for all your needs",
                icon="Zap",
                image_url="https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=600&q=80",
            ),
            Category(
                name="Painting",
                slug="painting",
                description="Transform your space with professional painting",
                icon="Paintbrush",
                image_url="https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=600&q=80",
            ),
            Category(
                name="Pest Control",
                slug="pest-control",
                description="Effective pest control solutions for your home",
                icon="Bug",
                image_url="https://images.unsplash.com/photo-1540366244940-9dce0a570312?w=600&q=80",
            ),
            Category(
                name="Maid Service",
                slug="maid-service",
                description="Reliable housekeeping and cleaning services for your home",
                icon="SprayCan",
                image_url="https://images.unsplash.com/photo-1575467678930-c7acd65d6470?w=600&q=80",
            ),
            Category(
                name="Chefs",
                slug="chefs",
                description="Professional chefs and cooking services for any occasion",
                icon="ChefHat",
                image_url="https://images.unsplash.com/photo-1681270543584-8e541a1bb056?w=600&q=80",
            ),
            Category(
                name="AC & Cooling",
                slug="ac-cooling",
                description="AC installation, repair, and maintenance",
                icon="Snowflake",
                image_url="https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80",
            ),
            Category(
                name="Handyman",
                slug="handyman",
                description="General repairs and odd jobs done right",
                icon="Hammer",
                image_url="https://images.unsplash.com/photo-1574359411659-15573a27fd0c?w=600&q=80",
            ),
            Category(
                name="Moving & Packing",
                slug="moving-packing",
                description="Stress-free moving and packing services",
                icon="Truck",
                image_url="https://images.unsplash.com/photo-1600518464441-9154a4dea21b?w=600&q=80",
            ),
        ]
        db.add_all(categories)
        db.flush()

        providers = [
            # Cleaning
            Provider(
                name="Dania Maids",
                slug="dania-maids",
                category="Cleaning",
                description="Qatar's highest-rated cleaning company since 1998. BICSc accredited with over 1,381 five-star reviews. Professional home, villa, and office cleaning at affordable rates starting from 35 QAR/hr.",
                rating=4.9,
                reviews_count=1381,
                price_range="QAR 35 - 180/hr",
                phone="+974 3333 7410",
                email="info@dania-maids.com",
                skills='["Home Cleaning", "Villa Cleaning", "Office Cleaning", "Deep Cleaning", "Eco-Friendly Products"]',
            ),
            Provider(
                name="Qatar Maid Service",
                slug="qatar-maid-service",
                category="Cleaning",
                description="Leading residential and corporate cleaning company in Doha. Professional housekeeping, deep cleaning, and sanitization services with flexible scheduling.",
                rating=4.7,
                reviews_count=423,
                price_range="QAR 80 - 250",
                phone="+974 3024 4939",
                email="info@qatarmaidservice.com",
                skills='["Residential Cleaning", "Deep Cleaning", "Office Cleaning", "Sanitization", "Pool Cleaning"]',
            ),
            Provider(
                name="Scrubs Qatar",
                slug="scrubs-qatar",
                category="Cleaning",
                description="Eco-friendly cleaning services using environmentally safe products. Trained professionals for home, apartment, and villa cleaning across Doha.",
                rating=4.6,
                reviews_count=187,
                price_range="QAR 60 - 200",
                phone="+974 5533 1221",
                email="hello@scrubs.qa",
                skills='["Eco Cleaning", "Home Cleaning", "Deep Cleaning", "Carpet Cleaning", "Move-in/Move-out"]',
            ),
            Provider(
                name="Al Allam Cleaning",
                slug="al-allam-cleaning",
                category="Cleaning",
                description="Professional cleaning and facility management since 2010. Offering house cleaning, office cleaning, steam cleaning, and babysitting services with trained staff.",
                rating=4.5,
                reviews_count=256,
                price_range="QAR 70 - 220",
                phone="+974 4411 5566",
                email="info@alallamcleaning.com",
                skills='["House Cleaning", "Office Cleaning", "Steam Cleaning", "Babysitting", "Laundry & Ironing"]',
            ),
            # Plumbing
            Provider(
                name="Home Service Qatar",
                slug="home-service-qatar",
                category="Plumbing",
                description="Expert plumbing services with 24/7 emergency response. Leak detection, pipe repair, water heater installation, and complete bathroom renovations. Certified plumbers.",
                rating=4.8,
                reviews_count=312,
                price_range="QAR 150 - 800",
                phone="+974 6643 1046",
                email="haquekamal42@gmail.com",
                skills='["Leak Detection", "Pipe Repair", "Water Heater Install", "Drain Cleaning", "Bathroom Renovation"]',
            ),
            Provider(
                name="Fixit Qatar",
                slug="fixit-qatar",
                category="Plumbing",
                description="Premium plumbing and maintenance services for homes and businesses. Full plumbing system diagnostics, repairs, and installations with guaranteed workmanship.",
                rating=4.7,
                reviews_count=198,
                price_range="QAR 180 - 750",
                phone="+974 3133 4948",
                email="helpdesk@fixitqatar.com",
                skills='["Full Plumbing", "Fixture Install", "Water Pressure Fix", "Sewer Line", "Emergency Service"]',
            ),
            Provider(
                name="Homefix Qatar",
                slug="homefix-qatar",
                category="Plumbing",
                description="All-in-one home maintenance with expert plumbing. Fast response for leaky faucets, burst pipes, toilet repairs, and complete bathroom fitting. Affordable fixed pricing.",
                rating=4.6,
                reviews_count=145,
                price_range="QAR 120 - 600",
                phone="+974 7401 4822",
                email="info@homefixqatar.com",
                skills='["Faucet Repair", "Toilet Repair", "Pipe Fixing", "Bathroom Fitting", "Water Tank Install"]',
            ),
            # Electrical
            Provider(
                name="Handyman Doha",
                slug="handyman-doha",
                category="Electrical",
                description="Professional electrical repair and installation services. Lighting, switches, sockets, wiring, and electrical fixing. Same-day service available across Doha.",
                rating=4.8,
                reviews_count=276,
                price_range="QAR 100 - 500",
                phone="+974 3332 0402",
                email="info@handymandoha.com",
                skills='["Lighting Install", "Switch Repair", "Wiring Work", "Socket Fixing", "Electrical Safety Check"]',
            ),
            Provider(
                name="Fixit Qatar",
                slug="fixit-qatar-electrical",
                category="Electrical",
                description="Licensed electricians for residential and commercial electrical work. Panel upgrades, rewiring, inspection, and smart home installation. Safety certified.",
                rating=4.7,
                reviews_count=167,
                price_range="QAR 150 - 700",
                phone="+974 3133 4948",
                email="helpdesk@fixitqatar.com",
                skills='["Panel Upgrade", "Rewiring", "Smart Home Setup", "Inspection", "Generator Connection"]',
            ),
            Provider(
                name="Homefix Qatar",
                slug="homefix-qatar-electrical",
                category="Electrical",
                description="Comprehensive electrical maintenance and repair. Switchboard repair, ceiling fan installation, emergency power solutions, and complete home rewiring.",
                rating=4.5,
                reviews_count=98,
                price_range="QAR 120 - 600",
                phone="+974 7401 4822",
                email="info@homefixqatar.com",
                skills='["Fan Installation", "Switchboard Repair", "Emergency Electric", "Ceiling Light Fix", "Wiring Upgrade"]',
            ),
            # Painting
            Provider(
                name="Homefix Qatar",
                slug="homefix-qatar-painting",
                category="Painting",
                description="Professional painting and decorating services for homes, villas, offices, and shops. Interior and exterior painting with premium materials and color consultation.",
                rating=4.7,
                reviews_count=134,
                price_range="QAR 200 - 1200",
                phone="+974 7401 4822",
                email="info@homefixqatar.com",
                skills='["Interior Painting", "Exterior Painting", "Color Consultation", "Wallpaper Install", "Texture Finish"]',
            ),
            Provider(
                name="Handyman Doha",
                slug="handyman-doha-painting",
                category="Painting",
                description="Quality painting and wall repair with professional finishing. Touch-ups, full room painting, crack repair, and decorative finishes. Quick and clean service.",
                rating=4.6,
                reviews_count=87,
                price_range="QAR 180 - 1000",
                phone="+974 3332 0402",
                email="info@handymandoha.com",
                skills='["Wall Painting", "Crack Repair", "Touch-ups", "Ceiling Painting", "Decorative Finish"]',
            ),
            Provider(
                name="Home Service Qatar",
                slug="home-service-qatar-painting",
                category="Painting",
                description="Complete painting solutions for residential and commercial properties. Professional prep work, premium paints, and meticulous attention to detail. Free quotes.",
                rating=4.5,
                reviews_count=72,
                price_range="QAR 200 - 1100",
                phone="+974 6643 1046",
                email="haquekamal42@gmail.com",
                skills='["House Painting", "Office Painting", "Wood Staining", "Waterproof Paint", "Free Quote"]',
            ),
            # Pest Control
            Provider(
                name="Al Allam Cleaning",
                slug="al-allam-pest-control",
                category="Pest Control",
                description="Effective pest control services as part of comprehensive facility management. Cockroach, ant, termite, and rodent elimination. Safe for families and pets.",
                rating=4.6,
                reviews_count=178,
                price_range="QAR 250 - 800",
                phone="+974 4411 5566",
                email="info@alallamcleaning.com",
                skills='["Cockroach Control", "Termite Treatment", "Rodent Control", "Ant Elimination", "Fumigation"]',
            ),
            Provider(
                name="Homefix Qatar",
                slug="homefix-qatar-pest",
                category="Pest Control",
                description="Residential and commercial pest management with integrated approach. Monthly and quarterly maintenance plans available. 100% satisfaction guaranteed.",
                rating=4.4,
                reviews_count=63,
                price_range="QAR 200 - 700",
                phone="+974 7401 4822",
                email="info@homefixqatar.com",
                skills='["Maintenance Plans", "Spider Control", "Fly Control", "Mosquito Treatment", "Prevention Tips"]',
            ),
            # AC & Cooling
            Provider(
                name="Homefix Qatar",
                slug="homefix-qatar-ac",
                category="AC & Cooling",
                description="AC installation, moving, repair, and maintenance. Water leak fixing, gas filling, compressor change, and complete AC servicing for all brands including LG, Samsung, Daikin.",
                rating=4.8,
                reviews_count=245,
                price_range="QAR 180 - 1500",
                phone="+974 7401 4822",
                email="info@homefixqatar.com",
                skills='["AC Installation", "AC Repair", "Gas Refill", "Compressor Fix", "AC Moving"]',
            ),
            Provider(
                name="Handyman Doha",
                slug="handyman-doha-ac",
                category="AC & Cooling",
                description="AC cleaning, servicing, installation support, and maintenance assistance. Quick response for emergency cooling issues across Doha and all Qatar.",
                rating=4.6,
                reviews_count=112,
                price_range="QAR 150 - 600",
                phone="+974 3332 0402",
                email="info@handymandoha.com",
                skills='["AC Cleaning", "AC Service", "AC Installation", "Duct Cleaning", "Filter Replacement"]',
            ),
            Provider(
                name="Home Service Qatar",
                slug="home-service-qatar-ac",
                category="AC & Cooling",
                description="Professional AC servicing and repair with 24/7 emergency support. Split AC, central AC, and ducted system maintenance. Energy efficiency optimization.",
                rating=4.5,
                reviews_count=89,
                price_range="QAR 200 - 1000",
                phone="+974 6643 1046",
                email="haquekamal42@gmail.com",
                skills='["Split AC Service", "Central AC", "Emergency Repair", "Energy Optimization", "Thermostat Setup"]',
            ),
            # Handyman
            Provider(
                name="Handyman Doha",
                slug="handyman-doha-main",
                category="Handyman",
                description="Trusted handyman company across Doha and all Qatar. Reliable repair, installation, and maintenance for homes and offices. Furniture assembly, TV mounting, door locks, and more.",
                rating=4.8,
                reviews_count=376,
                price_range="QAR 100 - 500",
                phone="+974 3332 0402",
                email="info@handymandoha.com",
                skills='["Furniture Assembly", "TV Mounting", "Door Repair", "General Repairs", "Shelf Installation"]',
            ),
            Provider(
                name="Homefix Qatar",
                slug="homefix-qatar-handyman",
                category="Handyman",
                description="One-stop solution for all home maintenance. Tile work, gypsum decoration, curtain installation, sofa upholstery, carpentry, and general handyman services.",
                rating=4.7,
                reviews_count=234,
                price_range="QAR 120 - 550",
                phone="+974 7401 4822",
                email="info@homefixqatar.com",
                skills='["Carpentry", "Tiling", "Gypsum Work", "Curtain Install", "Upholstery"]',
            ),
            Provider(
                name="Home Service Qatar",
                slug="home-service-qatar-handyman",
                category="Handyman",
                description="Complete house maintenance service with 24/7 availability. Plumbing, electrical, carpentry, painting, tile installation, and general repair solutions. Fast response.",
                rating=4.6,
                reviews_count=156,
                price_range="QAR 100 - 500",
                phone="+974 6643 1046",
                email="haquekamal42@gmail.com",
                skills='["General Maintenance", "Carpentry", "Tile Install", "Painting", "Emergency Repairs"]',
            ),
            Provider(
                name="Fixit Qatar",
                slug="fixit-qatar-handyman",
                category="Handyman",
                description="Hourly handyman service for all household repairs. Tile repairs, window seals, appliance fixing, shelf mounting, and more. Send us your task list.",
                rating=4.5,
                reviews_count=89,
                price_range="QAR 100 - 450",
                phone="+974 3133 4948",
                email="helpdesk@fixitqatar.com",
                skills='["Task List Service", "Appliance Repair", "Window Seal", "Tile Repair", "Shelf Mounting"]',
            ),
            # Moving & Packing
            Provider(
                name="Almas Movers International",
                slug="almas-movers",
                category="Moving & Packing",
                description="ISO-certified moving company since 2011. Residential, commercial, and international relocation services. IAM accredited with expert packing, transport, and setup.",
                rating=4.9,
                reviews_count=567,
                price_range="QAR 600 - 4000",
                phone="+974 4435 5663",
                email="movers@almasintl.com",
                skills='["Home Relocation", "Office Moving", "International Move", "Packing Service", "Furniture Setup"]',
            ),
            Provider(
                name="Qatar Movers and Packers",
                slug="qatar-movers-packers",
                category="Moving & Packing",
                description="Best moving company with expert packing, loading, and transportation across Doha, Al Khor, Lusail, and all Qatar. Fast, safe, and affordable relocation services.",
                rating=4.7,
                reviews_count=342,
                price_range="QAR 500 - 3000",
                phone="+974 3119 2915",
                email="info@qatarmoversandpackers.com",
                skills='["Home Relocation", "Office Shifting", "Furniture Moving", "Packing & Unpacking", "Loading Services"]',
            ),
            Provider(
                name="E-Movers Qatar",
                slug="e-movers-qatar",
                category="Moving & Packing",
                description="ISO 9001:2015 certified relocation company. Specializing in home relocation, office relocation, storage, and furniture installation. 80%+ customer satisfaction rate.",
                rating=4.6,
                reviews_count=198,
                price_range="QAR 500 - 3500",
                phone="+974 4476 2244",
                email="info@emoversqatar.com",
                skills='["Home Relocation", "Office Relocation", "Storage", "Furniture Install", "International Move"]',
            ),
            Provider(
                name="Moving Company Doha Qatar",
                slug="moving-company-doha",
                category="Moving & Packing",
                description="Reliable local movers since 2009. House, villa, apartment moving, and relocation services. Professional packing materials delivery and furniture disassembly included.",
                rating=4.5,
                reviews_count=123,
                price_range="QAR 400 - 2500",
                phone="+974 7183 7300",
                email="info@movingcompanydohaqatar.com",
                skills='["House Moving", "Villa Moving", "Apartment Moving", "Box Delivery", "Furniture Disassembly"]',
            ),
            # Maid Service
            Provider(
                name="Dania Maids",
                slug="dania-maids-service",
                category="Maid Service",
                description="Qatar's most trusted maid service since 1998. 4.9-star rating with over 1,381 reviews. Background-checked Filipino cleaners, eco-friendly products, AI-powered booking.",
                rating=4.9,
                reviews_count=1381,
                price_range="QAR 35 - 150/hr",
                phone="+974 3333 7410",
                email="info@dania-maids.com",
                skills='["House Cleaning", "Villa Cleaning", "Deep Cleaning", "Regular Cleaning", "Eco-Friendly"]',
            ),
            Provider(
                name="Qatar Maid Service",
                slug="qatar-maid-service-maid",
                category="Maid Service",
                description="Premium maid and housekeeping services for homes, villas, and apartments in Doha. Regular cleaning, deep cleaning, and custom packages with flexible timing.",
                rating=4.7,
                reviews_count=532,
                price_range="QAR 60 - 200",
                phone="+974 3024 4939",
                email="info@qatarmaidservice.com",
                skills='["Full House Cleaning", "Deep Cleaning", "Regular Maintenance", "Kitchen Cleaning", "Bathroom Cleaning"]',
            ),
            Provider(
                name="Pick Maid Qatar",
                slug="pick-maid-qatar",
                category="Maid Service",
                description="Affordable maid service with trained professionals. House cleaning, babysitting, laundry, ironing, steam cleaning, and upholstery care. Flexible scheduling available.",
                rating=4.5,
                reviews_count=234,
                price_range="QAR 50 - 180",
                phone="+974 7719 9699",
                email="wecare@pickmaid.com",
                skills='["Home Cleaning", "Babysitting", "Laundry & Ironing", "Steam Cleaning", "Upholstery Care"]',
            ),
            # Chefs
            Provider(
                name="Layla Kitchen",
                slug="layla-kitchen",
                category="Chefs",
                description="Premium catering and private dining services in Doha. Specializing in corporate events, weddings, intimate gatherings, and daily meal subscriptions. Exquisite cuisine.",
                rating=4.9,
                reviews_count=178,
                price_range="QAR 200 - 800",
                phone="+974 5566 7788",
                email="info@layla-kitchen.com",
                skills='["Corporate Catering", "Private Dining", "Wedding Catering", "Daily Meal Plan", "Pastry Service"]',
            ),
            Provider(
                name="Take a Chef Doha",
                slug="take-a-chef-doha",
                category="Chefs",
                description="Platform connecting 90+ professional private chefs in Doha. Personalized menus for any occasion. From intimate dinners to large celebrations. Chef shops, cooks, and cleans up.",
                rating=4.8,
                reviews_count=98,
                price_range="QAR 250 - 1000",
                phone="+974 5077 8899",
                email="hello@takeachef.com",
                skills='["Private Chef", "Custom Menus", "Event Catering", "Cooking Class", "Dietary Planning"]',
            ),
            Provider(
                name="MiumMium Qatar",
                slug="miummium-qatar",
                category="Chefs",
                description="Voted best private chef experience. Professional chefs for romantic dinners, cooking classes, bachelorette parties, and weekly meal prep. Full service from shopping to cleanup.",
                rating=4.7,
                reviews_count=67,
                price_range="QAR 300 - 1200",
                phone="+974 5088 9900",
                email="doha@miummium.com",
                skills='["Romantic Dinner", "Cooking Class", "Meal Prep", "Party Catering", "Wine Pairing"]',
            ),
            # Salon & Grooming
            Provider(
                name="Enddi Beauty Salon & Makeup",
                slug="enddi-beauty-salon",
                category="Salon & Grooming",
                description="African hair care, braids, weaves, makeup, and bridal looks in Doha. Expert styling, protective styles, and flawless makeup for every occasion.",
                rating=4.9,
                reviews_count=234,
                price_range="QAR 80 - 500",
                phone="+974 6644 4347",
                email="enddibeautysalon@gmail.com",
                skills='["Hair Braiding", "Weaves & Extensions", "Bridal Makeup", "African Hair Care", "Nail Art"]',
            ),
            Provider(
                name="Roots Qatar",
                slug="roots-qatar",
                category="Salon & Grooming",
                description="Blonde specialist salon in Doha. Expert hair cutting, coloring, and treatments. Focus on hair health with careful consultation for your perfect shade.",
                rating=4.8,
                reviews_count=312,
                price_range="QAR 150 - 600",
                phone="+974 4411 4463",
                email="info@rootsqtr.com",
                skills='["Blonde Specialist", "Hair Coloring", "Haircut & Styling", "Hair Treatment", "Consultation"]',
            ),
            Provider(
                name="Te'masq Ladies Salon & Spa",
                slug="temasq-ladies-salon",
                category="Salon & Grooming",
                description="Total transformation salon and spa for ladies. Expert hair stylists, color specialists, facials, and full beauty treatments. Locations at Mall of Qatar and DoubleTree Hilton.",
                rating=4.8,
                reviews_count=198,
                price_range="QAR 200 - 800",
                phone="+974 3157 7777",
                email="info@temasq.com",
                skills='["Hair Styling", "Hair Color", "Facial Treatment", "Spa Services", "Beauty Consultation"]',
            ),
            Provider(
                name="The Clique",
                slug="the-clique-doha",
                category="Salon & Grooming",
                description="Premium hair, nails, and lashes salon owned by master stylist Bassam Rezk. Showcasing artistry and expertise with every haircut, color, and nail service.",
                rating=4.7,
                reviews_count=156,
                price_range="QAR 150 - 700",
                phone="+974 5552 1999",
                email="info@theclique.qa",
                skills='["Haircut & Styling", "Hair Color", "Nail Art", "Lash Extensions", "Bridal Services"]',
            ),
            Provider(
                name="Glam Bar",
                slug="glam-bar-doha",
                category="Salon & Grooming",
                description="Luxurious beauty destination offering organic hair treatments, nail services, and transformative beauty journeys. Locally sourced aloe vera hair treatments available.",
                rating=4.6,
                reviews_count=187,
                price_range="QAR 100 - 500",
                phone="+974 4038 9056",
                email="info@glambar.qa",
                skills='["Organic Hair Treatment", "Manicure", "Pedicure", "Nail Art", "Beauty Treatment"]',
            ),
            Provider(
                name="Eva Beauty Salon",
                slug="eva-beauty-salon",
                category="Salon & Grooming",
                description="Full-service beauty salon offering eyebrow threading, bridal makeup, makeup service, and hair styling. Popular destination in Garafa, Doha.",
                rating=4.5,
                reviews_count=112,
                price_range="QAR 60 - 400",
                phone="+974 5574 4660",
                email="info@evabeauty.com",
                skills='["Bridal Makeup", "Eyebrow Threading", "Makeup Service", "Hair Styling", "Facial"]',
            ),
            Provider(
                name="La Coupe Salon",
                slug="la-coupe-salon",
                category="Salon & Grooming",
                description="Elegant salon at Dusit D2 Hotel offering professional hair services, threading, and beauty treatments. Known for precision cuts and exceptional customer service.",
                rating=4.4,
                reviews_count=89,
                price_range="QAR 80 - 450",
                phone="+974 3340 0273",
                email="info@lacoupesalon.com",
                skills='["Haircut", "Threading", "Blow Dry", "Hair Color", "Styling"]',
            ),
        ]
        db.add_all(providers)
        db.commit()
    finally:
        db.close()
